/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int init(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int init_alloc_mem(void);
int init_init_mem(int mem);
void init_free_mem(int mem);
int init_checkout(void);
void init_release(int mem);
void init_incref(void);
void init_decref(void);
casadi_int init_n_in(void);
casadi_int init_n_out(void);
casadi_real init_default_in(casadi_int i);
const char* init_name_in(casadi_int i);
const char* init_name_out(casadi_int i);
const casadi_int* init_sparsity_in(casadi_int i);
const casadi_int* init_sparsity_out(casadi_int i);
int init_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define init_SZ_ARG 3
#define init_SZ_RES 2
#define init_SZ_IW 0
#define init_SZ_W 14
int predict(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int predict_alloc_mem(void);
int predict_init_mem(int mem);
void predict_free_mem(int mem);
int predict_checkout(void);
void predict_release(int mem);
void predict_incref(void);
void predict_decref(void);
casadi_int predict_n_in(void);
casadi_int predict_n_out(void);
casadi_real predict_default_in(casadi_int i);
const char* predict_name_in(casadi_int i);
const char* predict_name_out(casadi_int i);
const casadi_int* predict_sparsity_in(casadi_int i);
const casadi_int* predict_sparsity_out(casadi_int i);
int predict_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define predict_SZ_ARG 7
#define predict_SZ_RES 2
#define predict_SZ_IW 0
#define predict_SZ_W 157
int correct_mag(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int correct_mag_alloc_mem(void);
int correct_mag_init_mem(int mem);
void correct_mag_free_mem(int mem);
int correct_mag_checkout(void);
void correct_mag_release(int mem);
void correct_mag_incref(void);
void correct_mag_decref(void);
casadi_int correct_mag_n_in(void);
casadi_int correct_mag_n_out(void);
casadi_real correct_mag_default_in(casadi_int i);
const char* correct_mag_name_in(casadi_int i);
const char* correct_mag_name_out(casadi_int i);
const casadi_int* correct_mag_sparsity_in(casadi_int i);
const casadi_int* correct_mag_sparsity_out(casadi_int i);
int correct_mag_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define correct_mag_SZ_ARG 6
#define correct_mag_SZ_RES 6
#define correct_mag_SZ_IW 0
#define correct_mag_SZ_W 23
int correct_accel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int correct_accel_alloc_mem(void);
int correct_accel_init_mem(int mem);
void correct_accel_free_mem(int mem);
int correct_accel_checkout(void);
void correct_accel_release(int mem);
void correct_accel_incref(void);
void correct_accel_decref(void);
casadi_int correct_accel_n_in(void);
casadi_int correct_accel_n_out(void);
casadi_real correct_accel_default_in(casadi_int i);
const char* correct_accel_name_in(casadi_int i);
const char* correct_accel_name_out(casadi_int i);
const casadi_int* correct_accel_sparsity_in(casadi_int i);
const casadi_int* correct_accel_sparsity_out(casadi_int i);
int correct_accel_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define correct_accel_SZ_ARG 8
#define correct_accel_SZ_RES 6
#define correct_accel_SZ_IW 0
#define correct_accel_SZ_W 20
int get_state(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int get_state_alloc_mem(void);
int get_state_init_mem(int mem);
void get_state_free_mem(int mem);
int get_state_checkout(void);
void get_state_release(int mem);
void get_state_incref(void);
void get_state_decref(void);
casadi_int get_state_n_in(void);
casadi_int get_state_n_out(void);
casadi_real get_state_default_in(casadi_int i);
const char* get_state_name_in(casadi_int i);
const char* get_state_name_out(casadi_int i);
const casadi_int* get_state_sparsity_in(casadi_int i);
const casadi_int* get_state_sparsity_out(casadi_int i);
int get_state_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define get_state_SZ_ARG 1
#define get_state_SZ_RES 3
#define get_state_SZ_IW 0
#define get_state_SZ_W 9
int constants(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int constants_alloc_mem(void);
int constants_init_mem(int mem);
void constants_free_mem(int mem);
int constants_checkout(void);
void constants_release(int mem);
void constants_incref(void);
void constants_decref(void);
casadi_int constants_n_in(void);
casadi_int constants_n_out(void);
casadi_real constants_default_in(casadi_int i);
const char* constants_name_in(casadi_int i);
const char* constants_name_out(casadi_int i);
const casadi_int* constants_sparsity_in(casadi_int i);
const casadi_int* constants_sparsity_out(casadi_int i);
int constants_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define constants_SZ_ARG 0
#define constants_SZ_RES 2
#define constants_SZ_IW 0
#define constants_SZ_W 1
#ifdef __cplusplus
} /* extern "C" */
#endif
