/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
#define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
#define _CASADI_NAMESPACE_CONCAT(NS, ID) NS##ID
#define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
#define CASADI_PREFIX(ID) rover2d_##ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

casadi_real casadi_fabs(casadi_real x)
{
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
    return x > 0 ? x : -x;
#else
    return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x * x; }

static const casadi_int casadi_s0[7] = { 3, 1, 0, 3, 0, 1, 2 };
static const casadi_int casadi_s1[5] = { 1, 1, 0, 1, 0 };

/* predict:(i0[3],i1,i2,i3)->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    w[0] = arg[0] ? arg[0][2] : 0;
    w[1] = cos(w[0]);
    w[2] = arg[2] ? arg[2][0] : 0;
    w[3] = arg[3] ? arg[3][0] : 0;
    w[3] = (w[2] / w[3]);
    w[4] = arg[1] ? arg[1][0] : 0;
    w[4] = tan(w[4]);
    w[3] = (w[3] * w[4]);
    w[4] = casadi_fabs(w[3]);
    w[5] = 9.9999999999999995e-08;
    w[4] = (w[4] < w[5]);
    w[6] = 1.;
    w[7] = -1.6666666666666666e-01;
    w[8] = casadi_sq(w[3]);
    w[7] = (w[7] * w[8]);
    w[7] = (w[6] + w[7]);
    w[8] = 8.3333333333333332e-03;
    w[9] = casadi_sq(w[3]);
    w[9] = casadi_sq(w[9]);
    w[8] = (w[8] * w[9]);
    w[7] = (w[7] + w[8]);
    w[7] = (w[4] ? w[7] : 0);
    w[4] = (!w[4]);
    w[8] = sin(w[3]);
    w[8] = (w[8] / w[3]);
    w[4] = (w[4] ? w[8] : 0);
    w[7] = (w[7] + w[4]);
    w[7] = (w[7] * w[2]);
    w[4] = (w[1] * w[7]);
    w[8] = sin(w[0]);
    w[9] = casadi_fabs(w[3]);
    w[9] = (w[9] < w[5]);
    w[5] = 5.0000000000000000e-01;
    w[5] = (w[5] * w[3]);
    w[10] = -4.1666666666666664e-02;
    w[11] = casadi_sq(w[3]);
    w[11] = (w[3] * w[11]);
    w[10] = (w[10] * w[11]);
    w[5] = (w[5] + w[10]);
    w[10] = 1.3888888888888889e-03;
    w[11] = casadi_sq(w[3]);
    w[11] = casadi_sq(w[11]);
    w[11] = (w[3] * w[11]);
    w[10] = (w[10] * w[11]);
    w[5] = (w[5] + w[10]);
    w[5] = (w[9] ? w[5] : 0);
    w[9] = (!w[9]);
    w[10] = cos(w[3]);
    w[6] = (w[6] - w[10]);
    w[6] = (w[6] / w[3]);
    w[9] = (w[9] ? w[6] : 0);
    w[5] = (w[5] + w[9]);
    w[5] = (w[5] * w[2]);
    w[2] = (w[8] * w[5]);
    w[4] = (w[4] - w[2]);
    w[2] = arg[0] ? arg[0][0] : 0;
    w[4] = (w[4] + w[2]);
    if (res[0] != 0)
        res[0][0] = w[4];
    w[8] = (w[8] * w[7]);
    w[1] = (w[1] * w[5]);
    w[8] = (w[8] + w[1]);
    w[1] = arg[0] ? arg[0][1] : 0;
    w[8] = (w[8] + w[1]);
    if (res[0] != 0)
        res[0][1] = w[8];
    w[0] = (w[0] + w[3]);
    if (res[0] != 0)
        res[0][2] = w[0];
    return 0;
}

int predict(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f0(arg, res, iw, w, mem);
}

int predict_alloc_mem(void)
{
    return 0;
}

int predict_init_mem(int mem)
{
    return 0;
}

void predict_free_mem(int mem)
{
}

int predict_checkout(void)
{
    return 0;
}

void predict_release(int mem)
{
}

void predict_incref(void)
{
}

void predict_decref(void)
{
}

casadi_int predict_n_in(void) { return 4; }

casadi_int predict_n_out(void) { return 1; }

casadi_real predict_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

const char* predict_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "i0";
    case 1:
        return "i1";
    case 2:
        return "i2";
    case 3:
        return "i3";
    default:
        return 0;
    }
}

const char* predict_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "o0";
    default:
        return 0;
    }
}

const casadi_int* predict_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s0;
    case 1:
        return casadi_s1;
    case 2:
        return casadi_s1;
    case 3:
        return casadi_s1;
    default:
        return 0;
    }
}

const casadi_int* predict_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s0;
    default:
        return 0;
    }
}

int predict_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 4;
    if (sz_res)
        *sz_res = 1;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 12;
    return 0;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
