# WARNING. THIS FILE IS AUTO-GENERATED. DO NOT MODIFY!
#
# This file contains build system settings derived from your snippets.
# Its contents are an implementation detail that should not be used outside
# of Zephyr's snippets CMake module.
#
# See the Snippets guide in the Zephyr documentation for more information.

###############################################################################
# Global information about all snippets.

# The name of every snippet that was discovered.
set(SNIPPET_NAMES "bt-ll-sw-split" "cdc-acm-console" "flash-16M" "flash-32M" "flash-4M" "flash-8M" "hci-uart-native-sim" "nordic-flpr" "nordic-flpr-xip" "nordic-log-stm" "nordic-log-stm-dict" "nordic-log-stm-tpiu-dict" "nordic-ppr" "nordic-ppr-xip" "nus-console" "psram-2M" "psram-4M" "psram-8M" "psram-reloc" "psram-wifi" "ram-console" "ram-tracing" "rp2-boot-mode-retention" "rtt-console" "rtt-tracing" "semihost-tracing" "serial-console" "silabs-pti" "socketcan-native-sim" "usbip-native-sim" "video-sw-generator" "wifi-credentials" "wifi-enterprise" "wifi-ip" "wifi-ipv4" "wifi-ipv6" "xen_dom0" "xiao-serial-console")
# The paths to all the snippet.yml files. One snippet
# can have multiple snippet.yml files.
set(SNIPPET_PATHS "/home/jgoppert/cognipilot/ws/zephyr/snippets/bt-ll-sw-split/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/cdc-acm-console/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/flash-16M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/flash-32M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/flash-4M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/flash-8M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/psram-2M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/psram-4M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/psram-8M/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/psram-reloc/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/espressif/psram-wifi/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/hci-uart-native-sim/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-flpr-xip/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-flpr/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-log-stm-dict/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-log-stm-tpiu-dict/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-log-stm/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-ppr-xip/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nordic/nordic-ppr/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/nus-console/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/ram-console/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/ram-tracing/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/rp2-boot-mode-retention/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/rtt-console/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/rtt-tracing/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/semihost-tracing/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/serial-console/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/silabs-pti/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/socketcan-native-sim/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/usbip-native-sim/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/video-sw-generator/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/wifi/wifi-credentials/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/wifi/wifi-enterprise/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/wifi/wifi-ip/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/wifi/wifi-ipv4/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/wifi/wifi-ipv6/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/xen_dom0/snippet.yml" "/home/jgoppert/cognipilot/ws/zephyr/snippets/xiao-serial-console/snippet.yml")

# Create variable scope for snippets build variables
zephyr_create_scope(snippets)

