
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      The target system is: Generic - 4.3.0 - posix
      The host system is: Linux - 6.17.0-19-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/jgoppert/cognipilot/ws/cerebri/build-native_sim/CMakeFiles/3.28.3/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/jgoppert/cognipilot/ws/cerebri/build-native_sim/CMakeFiles/3.28.3/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "/home/jgoppert/cognipilot/ws/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/jgoppert/cognipilot/ws/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
      Copyright (C) 2023 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
