# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 806b37ff02adcb8265f4e1713cec7d2f5f623fc0 # zephyr_3.7.0.1 08/21/24
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - cmsis-dsp
          - ubxlib
          - fatfs
          - segger
    - name: zros
      remote: cognipilot
      revision: 843348bca3a15e914914b90057369b9616302e20 # main 6/11/25
      path: modules/lib/zros
    - name: cyecca
      remote: cognipilot
      revision: afd329aaae3884943473cc92c91bc9216f263cf1 # incoming 19/06/25
      path: modules/lib/cyecca
    - name: synapse_pb
      remote: cognipilot
      revision: be99b693c321e3c97e785fe447e056792d89fe34 # main 8/22/24
      path: modules/lib/synapse_pb
    - name: ubxlib
      remote: cognipilot
      path: modules/lib/ubxlib
      revision: brave
    - name: hal_nxp
      remote: cognipilot
      revision: e400b5dba27d9abe1403fc799d48b58fa1b1daee # master 8/21/24
      path: modules/hal/nxp
