# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 296bdc1e5b0a72c9fb8083a330c3810760dddef8 # crsf 01/25/26
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - cmsis-dsp
          - cmsis_6
          - fatfs
          - open-amp
          - libmetal
          - segger
    - name: zros
      remote: cognipilot
      revision: 843348bca3a15e914914b90057369b9616302e20 # main 10/27/25
      path: modules/lib/zros
    - name: cyecca
      remote: cognipilot
      revision: 64d1f0dc5127d85765909f0c3525cc38305dac19 # main 11/17/25
      path: modules/lib/cyecca
    - name: synapse_pb
      remote: cognipilot
      revision: f038dd178faac0481033e5e4c757e31777c1b0be # main 11/10/25
      path: modules/lib/synapse_pb
    - name: hal_nxp
      remote: cognipilot
      revision: cf8f1631e862528ee044850bcc70273975b90771 # master 10/27/25
      path: modules/hal/nxp
    - name: zros_drivers
      remote: cognipilot
      revision: e0b37b4ae5f03f9bc985bf6f00fce2aee16b8e84 # main 01/06/26
      path: modules/lib/zros_drivers
    - name: zephyr_boards
      remote: cognipilot
      revision: b71c4264d4368e086dfca4da63f659b104938825 # tropic-crsf
      path: modules/lib/zephyr_boards
