# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cogniPilot
      url-base: https://github.com/cogniPilot

  projects:
    - name: zephyr
      url: https://github.com/CogniPilot/Zephyr
      clone-depth: 1
      west-commands: scripts/west-commands.yml
      revision: dev
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
    - name: synapse_tinyframe
      url: https://github.com/CogniPilot/synapse_tinyframe
      clone-depth: 1
      revision: main
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      url: https://github.com/CogniPilot/synapse_protobuf
      clone-depth: 1
      revision: main
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cogniPilot
      path: ubxlib
      revision: zephyr-3.4-compile-fix
      clone-depth: 1
