# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 9ada8966d5a440614d28bd7f5fda86fe96bf6ba8 # qdec-tested 11/6/23
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
    - name: synapse_tinyframe
      remote: cognipilot
      revision: dab568f2b81b928dc9516f7f02ab85ce1f93a7cc # main 11/8/23
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      remote: cognipilot
      revision: 1767c3a088343bcc3307b68842d7dfa028ac7c74 # main 11/8/23
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cognipilot
      path: ubxlib
      revision: 10d8042b41a197228df32425f32c3d65f28bcf59 # zephyr-3.4-compile-fix 7/19/23
