# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot
    - name: nxphovergames
      url-base: git@github.com:NXPHovergames

  projects:
    - name: zephyr
      remote: nxphovergames
      repo-path: Zephyr-Private
      west-commands: scripts/west-commands.yml
      revision: 0a17ae4f2f435e4bddcc3fb3febd90c019ede315
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - cmsis-dsp
          - ubxlib
          - fatfs
          - open-amp
          - libmetal
          - segger
    - name: zros
      remote: cognipilot
      revision: 93de4213e5c6c1a3cf1f879ed1e6e4e0b7cb2ae5 # main 8/07/24
      path: modules/lib/zros
    - name: cyecca
      remote: cognipilot
      revision: 45f92d1107e350504ed8dad4e526aedf0843490b # main 12/1/24
      path: modules/lib/cyecca
    - name: synapse_pb
      remote: cognipilot
      revision: be99b693c321e3c97e785fe447e056792d89fe34 # main 8/22/24
      path: modules/lib/synapse_pb
    - name: ubxlib
      remote: cognipilot
      path: modules/lib/ubxlib
      revision: brave
