# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: dev
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
    - name: synapse_tinyframe
      remote: cognipilot
      revision: main
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      remote: cognipilot
      revision: main
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cognipilot
      path: ubxlib
      revision: zephyr-3.4-compile-fix
