# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 61471d5a49cf0cb57845c5e3203e4dc4f0da34e2 # zephyr_cogni-3.6-v0
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
          - fatfs
          - littlefs
          - segger
    - name: zros
      remote: cognipilot
      revision: 739d990b9f613468c11941cecf6ef45b4485336b # main 6/05/24
      path: modules/lib/zros
    - name: synapse_tinyframe
      remote: cognipilot
      revision: 8519bc691293b85ad7073aae50eb3f17b5eacffc # pr-input 6/11/24
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      remote: cognipilot
      revision: 6a2554e862e285b8fe0194ca1e78918168de05bf # pr-input 6/11/24
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cognipilot
      path: modules/lib/ubxlib
      revision: 9c485ed5ab663b96cae6199498356fd13ee35904 # b_mythical 04/12/24
    - name: hal_nxp
      remote: cognipilot
      revision: a092d490a5bd7ed2db6fceb8c0b720cb4ead099a # pr-qtmr-pwm
      path: modules/hal/nxp
