# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 57e70b355f3a98fc93553b9012cc6d64a1c773a6 # main-with-patches 10/30/25
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - cmsis-dsp
          - cmsis_6
          - ubxlib
          - fatfs
          - segger
    - name: zros
      remote: cognipilot
      revision: 843348bca3a15e914914b90057369b9616302e20 # main 10/27/25
      path: modules/lib/zros
    - name: cyecca
      remote: cognipilot
      revision: cae27fd7e884770986f5fac136483b53df5e0839 # main 11/1/25
      path: modules/lib/cyecca
    - name: synapse_pb
      remote: cognipilot
      revision: e77c3a61f0ea8df8cf3424c9bd0bc33b28e53ba7 # main 10/27/25
      path: modules/lib/synapse_pb
    - name: ubxlib
      remote: cognipilot
      path: modules/lib/ubxlib
      revision: brave
    - name: hal_nxp
      remote: cognipilot
      revision: cf8f1631e862528ee044850bcc70273975b90771 # master 10/27/25
      path: modules/hal/nxp
    - name: zros_drivers
      remote: cognipilot
      revision: e6f30e7429cd46a1ce8a2723e735d9bfd6ecec20 # main 10/31/25
      path: modules/lib/zros_drivers
