# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: 2700c09c5186da7a1a9f227297aef80083fb2b16 # qdec-tested 11/5/23
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
    - name: synapse_tinyframe
      remote: cognipilot
      revision: db5a222aad74e260c21ba2c79b306be90da4cd63 # main 11/5/23
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      remote: cognipilot
      revision: f243208134024ceb350e7e6810edd03ed7b4054e # main 11/5/23
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cognipilot
      path: ubxlib
      revision: 10d8042b41a197228df32425f32c3d65f28bcf59 # zephyr-3.4-compile-fix 7/19/23
