# Copyright (c) 2023 CogniPilot Foundation
# SPDX-License-Identifier: Apache-2.0

manifest:

  group-filter:
    - +optional

  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cognipilot
      url-base: https://github.com/CogniPilot

  projects:
    - name: zephyr
      remote: cognipilot
      west-commands: scripts/west-commands.yml
      revision: e82fa68099ab6fd357881eadce1f0c3ffec463b9 # temp_dev 10/20/23
      import:
        - name-allowlist:
          - nanopb
          - mbedtls
          - hal_nxp
          - cmsis
          - ubxlib
    - name: synapse_tinyframe
      remote: cognipilot
      revision: a566447d677030975d398b23485d778b59c5325e # pr-mutex-fix 10/29/23
      path: modules/lib/synapse_tinyframe
    - name: synapse_protobuf
      remote: cognipilot
      revision: 2501f24d57a4a485cd745514287f927ed577e10e # main 10/6/23
      path: modules/lib/synapse_protobuf
    - name: ubxlib
      remote: cognipilot
      path: ubxlib
      revision: 10d8042b41a197228df32425f32c3d65f28bcf59 # zephyr-3.4-compile-fix 7/19/23
