version: "3.9"

volumes:
    # remembers gz config, downloaded models etc
    gz_config:

services:

  cerebri:
    extends:
      file: docker-compose.yml
      service: cerebri

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
