/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
#define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
#define _CASADI_NAMESPACE_CONCAT(NS, ID) NS##ID
#define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
#define CASADI_PREFIX(ID) casadi_mrp_##ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define CASADI_SYMBOL_EXPORT
#else
#define CASADI_SYMBOL_EXPORT __declspec(dllexport)
#endif
#elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define CASADI_SYMBOL_EXPORT __attribute__((visibility("default")))
#else
#define CASADI_SYMBOL_EXPORT
#endif
#endif

casadi_real casadi_sq(casadi_real x)
{
    return x * x;
}

casadi_real casadi_fabs(casadi_real x)
{
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
    return x > 0 ? x : -x;
#else
    return fabs(x);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y)
{
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
    return x > y ? x : y;
#else
    return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[7] = { 3, 1, 0, 3, 0, 1, 2 };
static const casadi_int casadi_s1[5] = { 1, 1, 0, 1, 0 };
static const casadi_int casadi_s2[11] = { 7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6 };
static const casadi_int casadi_s3[30] = { 6, 6, 0, 6, 11, 15, 18, 20, 21, 0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5 };
static const casadi_int casadi_s4[6] = { 2, 1, 0, 2, 0, 1 };
static const casadi_int casadi_s5[8] = { 4, 1, 0, 4, 0, 1, 2, 3 };
static const casadi_int casadi_s6[15] = { 6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5 };

/* init:(g_b[3],B_b[3],decl)->(x0[7],error_code) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
    a0 = 0.;
    if (res[0] != 0)
        res[0][0] = a0;
    if (res[0] != 0)
        res[0][1] = a0;
    if (res[0] != 0)
        res[0][2] = a0;
    if (res[0] != 0)
        res[0][3] = a0;
    if (res[0] != 0)
        res[0][4] = a0;
    if (res[0] != 0)
        res[0][5] = a0;
    if (res[0] != 0)
        res[0][6] = a0;
    a1 = 1.;
    a2 = arg[0] ? arg[0][0] : 0;
    a3 = casadi_sq(a2);
    a4 = arg[0] ? arg[0][1] : 0;
    a5 = casadi_sq(a4);
    a3 = (a3 + a5);
    a5 = arg[0] ? arg[0][2] : 0;
    a6 = casadi_sq(a5);
    a3 = (a3 + a6);
    a3 = sqrt(a3);
    a6 = 9.8000000000000007e+00;
    a6 = (a3 - a6);
    a6 = casadi_fabs(a6);
    a6 = (a1 < a6);
    a1 = (a6 ? a1 : 0);
    a6 = (!a6);
    a7 = arg[1] ? arg[1][0] : 0;
    a8 = casadi_sq(a7);
    a9 = arg[1] ? arg[1][1] : 0;
    a10 = casadi_sq(a9);
    a8 = (a8 + a10);
    a10 = arg[1] ? arg[1][2] : 0;
    a11 = casadi_sq(a10);
    a8 = (a8 + a11);
    a8 = sqrt(a8);
    a0 = (a8 <= a0);
    a11 = 2.;
    a11 = (a0 ? a11 : 0);
    a0 = (!a0);
    a5 = (a5 / a3);
    a9 = (a9 / a8);
    a12 = (a5 * a9);
    a4 = (a4 / a3);
    a10 = (a10 / a8);
    a13 = (a4 * a10);
    a12 = (a12 - a13);
    a12 = casadi_sq(a12);
    a2 = (a2 / a3);
    a10 = (a2 * a10);
    a7 = (a7 / a8);
    a5 = (a5 * a7);
    a10 = (a10 - a5);
    a10 = casadi_sq(a10);
    a12 = (a12 + a10);
    a4 = (a4 * a7);
    a2 = (a2 * a9);
    a4 = (a4 - a2);
    a4 = casadi_sq(a4);
    a12 = (a12 + a4);
    a12 = sqrt(a12);
    a12 = asin(a12);
    a4 = 1.7453292519943295e-01;
    a12 = (a12 < a4);
    a4 = 3.;
    a12 = (a12 ? a4 : 0);
    a0 = (a0 ? a12 : 0);
    a11 = (a11 + a0);
    a6 = (a6 ? a11 : 0);
    a1 = (a1 + a6);
    if (res[1] != 0)
        res[1][0] = a1;
    return 0;
}

CASADI_SYMBOL_EXPORT int init(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int init_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int init_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void init_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int init_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void init_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void init_incref(void)
{
}

CASADI_SYMBOL_EXPORT void init_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int init_n_in(void) { return 3; }

CASADI_SYMBOL_EXPORT casadi_int init_n_out(void) { return 2; }

CASADI_SYMBOL_EXPORT casadi_real init_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* init_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "g_b";
    case 1:
        return "B_b";
    case 2:
        return "decl";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* init_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "x0";
    case 1:
        return "error_code";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* init_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s0;
    case 1:
        return casadi_s0;
    case 2:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* init_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int init_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 3;
    if (sz_res)
        *sz_res = 2;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

/* predict:(t,x[7],W[6x6,21nz],omega_m[3],std_gyro,sn_gyro_rw,dt)->(x1[7],W1[6x6,21nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a156, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
    a0 = 1.;
    a1 = arg[1] ? arg[1][0] : 0;
    a2 = arg[6] ? arg[6][0] : 0;
    a3 = 2.5000000000000000e-01;
    a4 = casadi_sq(a1);
    a5 = arg[1] ? arg[1][1] : 0;
    a6 = casadi_sq(a5);
    a4 = (a4 + a6);
    a6 = arg[1] ? arg[1][2] : 0;
    a7 = casadi_sq(a6);
    a4 = (a4 + a7);
    a4 = (a0 - a4);
    a7 = 2.;
    a8 = (a7 * a1);
    a9 = (a8 * a1);
    a9 = (a4 + a9);
    a9 = (a3 * a9);
    a10 = arg[3] ? arg[3][0] : 0;
    a11 = arg[1] ? arg[1][4] : 0;
    a10 = (a10 - a11);
    a9 = (a9 * a10);
    a12 = (a8 * a5);
    a13 = (a7 * a6);
    a12 = (a12 - a13);
    a12 = (a3 * a12);
    a13 = arg[3] ? arg[3][1] : 0;
    a14 = arg[1] ? arg[1][5] : 0;
    a13 = (a13 - a14);
    a12 = (a12 * a13);
    a9 = (a9 + a12);
    a12 = (a7 * a5);
    a8 = (a8 * a6);
    a12 = (a12 + a8);
    a12 = (a3 * a12);
    a8 = arg[3] ? arg[3][2] : 0;
    a15 = arg[1] ? arg[1][6] : 0;
    a8 = (a8 - a15);
    a12 = (a12 * a8);
    a9 = (a9 + a12);
    a9 = (a2 * a9);
    a12 = (a9 / a7);
    a12 = (a1 + a12);
    a16 = casadi_sq(a12);
    a17 = (a7 * a6);
    a18 = (a7 * a5);
    a19 = (a18 * a1);
    a17 = (a17 + a19);
    a17 = (a3 * a17);
    a17 = (a17 * a10);
    a19 = (a18 * a5);
    a19 = (a4 + a19);
    a19 = (a3 * a19);
    a19 = (a19 * a13);
    a17 = (a17 + a19);
    a18 = (a18 * a6);
    a19 = (a7 * a1);
    a18 = (a18 - a19);
    a18 = (a3 * a18);
    a18 = (a18 * a8);
    a17 = (a17 + a18);
    a17 = (a2 * a17);
    a18 = (a17 / a7);
    a18 = (a5 + a18);
    a19 = casadi_sq(a18);
    a16 = (a16 + a19);
    a19 = (a7 * a6);
    a20 = (a19 * a1);
    a21 = (a7 * a5);
    a20 = (a20 - a21);
    a20 = (a3 * a20);
    a20 = (a20 * a10);
    a21 = (a7 * a1);
    a22 = (a19 * a5);
    a21 = (a21 + a22);
    a21 = (a3 * a21);
    a21 = (a21 * a13);
    a20 = (a20 + a21);
    a19 = (a19 * a6);
    a4 = (a4 + a19);
    a4 = (a3 * a4);
    a4 = (a4 * a8);
    a20 = (a20 + a4);
    a20 = (a2 * a20);
    a4 = (a20 / a7);
    a4 = (a6 + a4);
    a19 = casadi_sq(a4);
    a16 = (a16 + a19);
    a16 = (a0 - a16);
    a19 = (a7 * a12);
    a21 = (a19 * a12);
    a21 = (a16 + a21);
    a21 = (a3 * a21);
    a21 = (a21 * a10);
    a22 = (a19 * a18);
    a23 = (a7 * a4);
    a22 = (a22 - a23);
    a22 = (a3 * a22);
    a22 = (a22 * a13);
    a21 = (a21 + a22);
    a22 = (a7 * a18);
    a19 = (a19 * a4);
    a22 = (a22 + a19);
    a22 = (a3 * a22);
    a22 = (a22 * a8);
    a21 = (a21 + a22);
    a21 = (a2 * a21);
    a22 = (a7 * a21);
    a9 = (a9 + a22);
    a21 = (a21 / a7);
    a21 = (a1 + a21);
    a22 = casadi_sq(a21);
    a19 = (a7 * a4);
    a23 = (a7 * a18);
    a24 = (a23 * a12);
    a19 = (a19 + a24);
    a19 = (a3 * a19);
    a19 = (a19 * a10);
    a24 = (a23 * a18);
    a24 = (a16 + a24);
    a24 = (a3 * a24);
    a24 = (a24 * a13);
    a19 = (a19 + a24);
    a23 = (a23 * a4);
    a24 = (a7 * a12);
    a23 = (a23 - a24);
    a23 = (a3 * a23);
    a23 = (a23 * a8);
    a19 = (a19 + a23);
    a19 = (a2 * a19);
    a23 = (a19 / a7);
    a23 = (a5 + a23);
    a24 = casadi_sq(a23);
    a22 = (a22 + a24);
    a24 = (a7 * a4);
    a25 = (a24 * a12);
    a26 = (a7 * a18);
    a25 = (a25 - a26);
    a25 = (a3 * a25);
    a25 = (a25 * a10);
    a12 = (a7 * a12);
    a18 = (a24 * a18);
    a12 = (a12 + a18);
    a12 = (a3 * a12);
    a12 = (a12 * a13);
    a25 = (a25 + a12);
    a24 = (a24 * a4);
    a16 = (a16 + a24);
    a16 = (a3 * a16);
    a16 = (a16 * a8);
    a25 = (a25 + a16);
    a25 = (a2 * a25);
    a16 = (a25 / a7);
    a16 = (a6 + a16);
    a24 = casadi_sq(a16);
    a22 = (a22 + a24);
    a22 = (a0 - a22);
    a24 = (a7 * a21);
    a4 = (a24 * a21);
    a4 = (a22 + a4);
    a4 = (a3 * a4);
    a4 = (a4 * a10);
    a12 = (a24 * a23);
    a18 = (a7 * a16);
    a12 = (a12 - a18);
    a12 = (a3 * a12);
    a12 = (a12 * a13);
    a4 = (a4 + a12);
    a12 = (a7 * a23);
    a24 = (a24 * a16);
    a12 = (a12 + a24);
    a12 = (a3 * a12);
    a12 = (a12 * a8);
    a4 = (a4 + a12);
    a4 = (a2 * a4);
    a12 = (a7 * a4);
    a9 = (a9 + a12);
    a4 = (a1 + a4);
    a12 = casadi_sq(a4);
    a24 = (a7 * a16);
    a18 = (a7 * a23);
    a26 = (a18 * a21);
    a24 = (a24 + a26);
    a24 = (a3 * a24);
    a24 = (a24 * a10);
    a26 = (a18 * a23);
    a26 = (a22 + a26);
    a26 = (a3 * a26);
    a26 = (a26 * a13);
    a24 = (a24 + a26);
    a18 = (a18 * a16);
    a26 = (a7 * a21);
    a18 = (a18 - a26);
    a18 = (a3 * a18);
    a18 = (a18 * a8);
    a24 = (a24 + a18);
    a24 = (a2 * a24);
    a18 = (a5 + a24);
    a26 = casadi_sq(a18);
    a12 = (a12 + a26);
    a26 = (a7 * a16);
    a27 = (a26 * a21);
    a28 = (a7 * a23);
    a27 = (a27 - a28);
    a27 = (a3 * a27);
    a27 = (a27 * a10);
    a21 = (a7 * a21);
    a23 = (a26 * a23);
    a21 = (a21 + a23);
    a21 = (a3 * a21);
    a21 = (a21 * a13);
    a27 = (a27 + a21);
    a26 = (a26 * a16);
    a22 = (a22 + a26);
    a22 = (a3 * a22);
    a22 = (a22 * a8);
    a27 = (a27 + a22);
    a27 = (a2 * a27);
    a22 = (a6 + a27);
    a26 = casadi_sq(a22);
    a12 = (a12 + a26);
    a12 = (a0 - a12);
    a26 = (a7 * a4);
    a16 = (a26 * a4);
    a16 = (a12 + a16);
    a16 = (a3 * a16);
    a16 = (a16 * a10);
    a21 = (a26 * a18);
    a23 = (a7 * a22);
    a21 = (a21 - a23);
    a21 = (a3 * a21);
    a21 = (a21 * a13);
    a16 = (a16 + a21);
    a21 = (a7 * a18);
    a26 = (a26 * a22);
    a21 = (a21 + a26);
    a21 = (a3 * a21);
    a21 = (a21 * a8);
    a16 = (a16 + a21);
    a16 = (a2 * a16);
    a9 = (a9 + a16);
    a16 = 6.;
    a9 = (a9 / a16);
    a9 = (a1 + a9);
    a21 = casadi_sq(a9);
    a19 = (a7 * a19);
    a17 = (a17 + a19);
    a24 = (a7 * a24);
    a17 = (a17 + a24);
    a24 = (a7 * a22);
    a19 = (a7 * a18);
    a26 = (a19 * a4);
    a24 = (a24 + a26);
    a24 = (a3 * a24);
    a24 = (a24 * a10);
    a26 = (a19 * a18);
    a26 = (a12 + a26);
    a26 = (a3 * a26);
    a26 = (a26 * a13);
    a24 = (a24 + a26);
    a19 = (a19 * a22);
    a26 = (a7 * a4);
    a19 = (a19 - a26);
    a19 = (a3 * a19);
    a19 = (a19 * a8);
    a24 = (a24 + a19);
    a24 = (a2 * a24);
    a17 = (a17 + a24);
    a17 = (a17 / a16);
    a17 = (a5 + a17);
    a24 = casadi_sq(a17);
    a21 = (a21 + a24);
    a25 = (a7 * a25);
    a20 = (a20 + a25);
    a27 = (a7 * a27);
    a20 = (a20 + a27);
    a27 = (a7 * a22);
    a25 = (a27 * a4);
    a24 = (a7 * a18);
    a25 = (a25 - a24);
    a25 = (a3 * a25);
    a25 = (a25 * a10);
    a4 = (a7 * a4);
    a18 = (a27 * a18);
    a4 = (a4 + a18);
    a4 = (a3 * a4);
    a4 = (a4 * a13);
    a25 = (a25 + a4);
    a27 = (a27 * a22);
    a12 = (a12 + a27);
    a3 = (a3 * a12);
    a3 = (a3 * a8);
    a25 = (a25 + a3);
    a25 = (a2 * a25);
    a20 = (a20 + a25);
    a20 = (a20 / a16);
    a20 = (a6 + a20);
    a25 = casadi_sq(a20);
    a21 = (a21 + a25);
    a21 = sqrt(a21);
    a21 = (a0 < a21);
    a25 = casadi_sq(a9);
    a3 = casadi_sq(a17);
    a25 = (a25 + a3);
    a3 = casadi_sq(a20);
    a25 = (a25 + a3);
    a3 = (a9 / a25);
    a3 = (-a3);
    a3 = (a21 ? a3 : 0);
    a8 = (!a21);
    a9 = (a8 ? a9 : 0);
    a3 = (a3 + a9);
    if (res[0] != 0)
        res[0][0] = a3;
    a3 = (a17 / a25);
    a3 = (-a3);
    a3 = (a21 ? a3 : 0);
    a17 = (a8 ? a17 : 0);
    a3 = (a3 + a17);
    if (res[0] != 0)
        res[0][1] = a3;
    a25 = (a20 / a25);
    a25 = (-a25);
    a25 = (a21 ? a25 : 0);
    a20 = (a8 ? a20 : 0);
    a25 = (a25 + a20);
    if (res[0] != 0)
        res[0][2] = a25;
    a25 = arg[1] ? arg[1][3] : 0;
    a20 = (!a25);
    a21 = (a21 ? a20 : 0);
    a8 = (a8 ? a25 : 0);
    a21 = (a21 + a8);
    if (res[0] != 0)
        res[0][3] = a21;
    if (res[0] != 0)
        res[0][4] = a11;
    if (res[0] != 0)
        res[0][5] = a14;
    if (res[0] != 0)
        res[0][6] = a15;
    a15 = arg[2] ? arg[2][0] : 0;
    a14 = arg[4] ? arg[4][0] : 0;
    a11 = casadi_sq(a14);
    a21 = (a11 / a7);
    a8 = (a21 / a15);
    a25 = 8.;
    a20 = casadi_sq(a6);
    a3 = casadi_sq(a5);
    a20 = (a20 + a3);
    a20 = (a25 * a20);
    a3 = casadi_sq(a1);
    a17 = casadi_sq(a5);
    a3 = (a3 + a17);
    a17 = casadi_sq(a6);
    a3 = (a3 + a17);
    a17 = (a0 + a3);
    a17 = casadi_sq(a17);
    a20 = (a20 / a17);
    a20 = (a0 - a20);
    a9 = arg[2] ? arg[2][3] : 0;
    a12 = (a20 * a9);
    a27 = (a1 * a5);
    a27 = (a25 * a27);
    a22 = 4.;
    a3 = (a0 - a3);
    a22 = (a22 * a3);
    a3 = (a22 * a6);
    a27 = (a27 - a3);
    a27 = (a27 / a17);
    a3 = arg[2] ? arg[2][4] : 0;
    a4 = (a27 * a3);
    a12 = (a12 + a4);
    a4 = (a1 * a6);
    a4 = (a25 * a4);
    a13 = (a22 * a5);
    a4 = (a4 + a13);
    a4 = (a4 / a17);
    a13 = arg[2] ? arg[2][5] : 0;
    a18 = (a4 * a13);
    a12 = (a12 + a18);
    a8 = (a8 - a12);
    a8 = (a2 * a8);
    a12 = (a8 / a7);
    a12 = (a15 + a12);
    a18 = (a21 / a12);
    a10 = arg[2] ? arg[2][12] : 0;
    a24 = arg[2] ? arg[2][11] : 0;
    a19 = (a10 / a24);
    a26 = arg[2] ? arg[2][15] : 0;
    a19 = (a19 / a26);
    a23 = arg[2] ? arg[2][7] : 0;
    a28 = arg[2] ? arg[2][6] : 0;
    a29 = (a23 / a28);
    a29 = (a29 / a24);
    a30 = arg[2] ? arg[2][8] : 0;
    a31 = (a20 * a30);
    a32 = arg[2] ? arg[2][9] : 0;
    a33 = (a27 * a32);
    a31 = (a31 + a33);
    a33 = arg[2] ? arg[2][10] : 0;
    a34 = (a4 * a33);
    a31 = (a31 + a34);
    a11 = (a11 / a7);
    a34 = arg[2] ? arg[2][1] : 0;
    a35 = (a34 / a15);
    a35 = (a35 / a28);
    a36 = (a11 * a35);
    a31 = (a31 + a36);
    a31 = (a31 * a28);
    a36 = (a29 * a31);
    a37 = (a23 * a35);
    a38 = arg[2] ? arg[2][2] : 0;
    a39 = (a38 / a15);
    a37 = (a37 - a39);
    a37 = (a37 / a24);
    a39 = (a11 * a37);
    a40 = (a20 * a10);
    a41 = arg[2] ? arg[2][13] : 0;
    a42 = (a27 * a41);
    a40 = (a40 + a42);
    a42 = arg[2] ? arg[2][14] : 0;
    a43 = (a4 * a42);
    a40 = (a40 + a43);
    a39 = (a39 - a40);
    a36 = (a36 - a39);
    a36 = (a36 * a24);
    a39 = (a19 * a36);
    a40 = (a30 * a35);
    a43 = (a9 / a15);
    a40 = (a40 - a43);
    a43 = (a10 * a37);
    a40 = (a40 - a43);
    a40 = (a40 / a26);
    a43 = (a11 * a40);
    a44 = (a20 * a26);
    a45 = arg[2] ? arg[2][16] : 0;
    a46 = (a27 * a45);
    a44 = (a44 + a46);
    a46 = arg[2] ? arg[2][17] : 0;
    a47 = (a4 * a46);
    a44 = (a44 + a47);
    a43 = (a43 - a44);
    a44 = (a10 * a29);
    a47 = (a30 / a28);
    a44 = (a44 - a47);
    a44 = (a44 / a26);
    a47 = (a44 * a31);
    a43 = (a43 + a47);
    a39 = (a39 - a43);
    a39 = (a39 * a26);
    a43 = (a39 / a15);
    a43 = (a2 * a43);
    a47 = (a43 / a7);
    a47 = (a9 - a47);
    a48 = (a20 * a47);
    a49 = (a45 / a26);
    a50 = arg[2] ? arg[2][18] : 0;
    a49 = (a49 / a50);
    a51 = (a49 * a39);
    a52 = (a32 * a35);
    a53 = (a3 / a15);
    a52 = (a52 - a53);
    a53 = (a41 * a37);
    a52 = (a52 - a53);
    a53 = (a45 * a40);
    a52 = (a52 - a53);
    a52 = (a52 / a50);
    a53 = (a11 * a52);
    a54 = (a27 * a50);
    a55 = arg[2] ? arg[2][19] : 0;
    a56 = (a4 * a55);
    a54 = (a54 + a56);
    a53 = (a53 - a54);
    a54 = (a41 * a29);
    a56 = (a32 / a28);
    a54 = (a54 - a56);
    a56 = (a45 * a44);
    a54 = (a54 - a56);
    a54 = (a54 / a50);
    a56 = (a54 * a31);
    a53 = (a53 + a56);
    a56 = (a45 * a19);
    a57 = (a41 / a24);
    a56 = (a56 - a57);
    a56 = (a56 / a50);
    a57 = (a56 * a36);
    a53 = (a53 + a57);
    a51 = (a51 - a53);
    a51 = (a51 * a50);
    a53 = (a51 / a15);
    a53 = (a2 * a53);
    a57 = (a53 / a7);
    a57 = (a3 - a57);
    a58 = (a27 * a57);
    a48 = (a48 + a58);
    a58 = (a55 / a50);
    a59 = arg[2] ? arg[2][20] : 0;
    a58 = (a58 / a59);
    a60 = (a58 * a51);
    a35 = (a33 * a35);
    a61 = (a13 / a15);
    a35 = (a35 - a61);
    a61 = (a42 * a37);
    a35 = (a35 - a61);
    a61 = (a46 * a40);
    a35 = (a35 - a61);
    a61 = (a55 * a52);
    a35 = (a35 - a61);
    a35 = (a35 / a59);
    a61 = (a11 * a35);
    a62 = (a4 * a59);
    a61 = (a61 - a62);
    a62 = (a42 * a29);
    a63 = (a33 / a28);
    a62 = (a62 - a63);
    a63 = (a46 * a44);
    a62 = (a62 - a63);
    a63 = (a55 * a54);
    a62 = (a62 - a63);
    a62 = (a62 / a59);
    a63 = (a62 * a31);
    a61 = (a61 + a63);
    a63 = (a46 * a19);
    a64 = (a42 / a24);
    a63 = (a63 - a64);
    a64 = (a55 * a56);
    a63 = (a63 - a64);
    a63 = (a63 / a59);
    a64 = (a63 * a36);
    a61 = (a61 + a64);
    a64 = (a55 * a49);
    a65 = (a46 / a26);
    a64 = (a64 - a65);
    a64 = (a64 / a59);
    a65 = (a64 * a39);
    a61 = (a61 + a65);
    a60 = (a60 - a61);
    a60 = (a60 * a59);
    a61 = (a60 / a15);
    a61 = (a2 * a61);
    a65 = (a61 / a7);
    a65 = (a13 - a65);
    a66 = (a4 * a65);
    a48 = (a48 + a66);
    a18 = (a18 - a48);
    a18 = (a2 * a18);
    a48 = (a7 * a18);
    a8 = (a8 + a48);
    a18 = (a18 / a7);
    a18 = (a15 + a18);
    a48 = (a21 / a18);
    a66 = (a40 * a31);
    a67 = casadi_sq(a14);
    a68 = (a67 / a7);
    a69 = (a68 * a44);
    a70 = (a5 * a1);
    a70 = (a25 * a70);
    a71 = (a22 * a6);
    a70 = (a70 + a71);
    a70 = (a70 / a17);
    a71 = (a70 * a26);
    a72 = casadi_sq(a6);
    a73 = casadi_sq(a1);
    a72 = (a72 + a73);
    a72 = (a25 * a72);
    a72 = (a72 / a17);
    a72 = (a0 - a72);
    a73 = (a72 * a45);
    a71 = (a71 + a73);
    a73 = (a5 * a6);
    a73 = (a25 * a73);
    a74 = (a22 * a1);
    a73 = (a73 - a74);
    a73 = (a73 / a17);
    a74 = (a73 * a46);
    a71 = (a71 + a74);
    a69 = (a69 - a71);
    a66 = (a66 - a69);
    a29 = (a68 * a29);
    a69 = (a70 * a10);
    a71 = (a72 * a41);
    a69 = (a69 + a71);
    a71 = (a73 * a42);
    a69 = (a69 + a71);
    a29 = (a29 + a69);
    a37 = (a37 * a31);
    a29 = (a29 + a37);
    a29 = (a29 * a24);
    a37 = (a19 * a29);
    a66 = (a66 + a37);
    a66 = (a66 * a26);
    a37 = (a23 / a28);
    a37 = (a37 / a24);
    a69 = (a66 * a37);
    a71 = (a34 / a15);
    a71 = (a71 / a28);
    a74 = (a23 * a71);
    a75 = (a38 / a15);
    a74 = (a74 - a75);
    a74 = (a74 / a24);
    a75 = (a39 * a74);
    a69 = (a69 - a75);
    a14 = casadi_sq(a14);
    a75 = (a14 / a7);
    a19 = (a75 * a19);
    a76 = (a6 * a1);
    a76 = (a25 * a76);
    a77 = (a22 * a5);
    a76 = (a76 - a77);
    a76 = (a76 / a17);
    a77 = (a76 * a26);
    a6 = (a6 * a5);
    a6 = (a25 * a6);
    a22 = (a22 * a1);
    a6 = (a6 + a22);
    a6 = (a6 / a17);
    a22 = (a6 * a45);
    a77 = (a77 + a22);
    a5 = casadi_sq(a5);
    a1 = casadi_sq(a1);
    a5 = (a5 + a1);
    a25 = (a25 * a5);
    a25 = (a25 / a17);
    a0 = (a0 - a25);
    a25 = (a0 * a46);
    a77 = (a77 + a25);
    a19 = (a19 + a77);
    a40 = (a40 * a36);
    a19 = (a19 + a40);
    a44 = (a44 * a29);
    a19 = (a19 + a44);
    a19 = (a19 * a26);
    a44 = (a19 / a24);
    a69 = (a69 - a44);
    a69 = (a2 * a69);
    a44 = (a69 / a7);
    a44 = (a10 + a44);
    a40 = (a29 * a37);
    a77 = (a36 * a74);
    a40 = (a40 - a77);
    a14 = (a14 / a7);
    a77 = (a14 / a24);
    a40 = (a40 + a77);
    a77 = (a76 * a10);
    a25 = (a6 * a41);
    a77 = (a77 + a25);
    a25 = (a0 * a42);
    a77 = (a77 + a25);
    a40 = (a40 - a77);
    a40 = (a2 * a40);
    a77 = (a40 / a7);
    a77 = (a24 + a77);
    a25 = (a44 / a77);
    a17 = (a10 / a24);
    a17 = (a17 / a26);
    a5 = (a19 * a17);
    a1 = (a30 * a71);
    a22 = (a9 / a15);
    a1 = (a1 - a22);
    a22 = (a10 * a74);
    a1 = (a1 - a22);
    a1 = (a1 / a26);
    a22 = (a39 * a1);
    a78 = (a10 * a37);
    a79 = (a30 / a28);
    a78 = (a78 - a79);
    a78 = (a78 / a26);
    a79 = (a66 * a78);
    a22 = (a22 + a79);
    a5 = (a5 - a22);
    a22 = arg[5] ? arg[5][0] : 0;
    a79 = sqrt(a2);
    a22 = (a22 / a79);
    a79 = casadi_sq(a22);
    a80 = (a79 / a7);
    a81 = (a80 / a26);
    a5 = (a5 + a81);
    a5 = (a2 * a5);
    a81 = (a5 / a7);
    a81 = (a26 + a81);
    a25 = (a25 / a81);
    a82 = (a36 * a71);
    a83 = (a29 / a28);
    a82 = (a82 - a83);
    a83 = (a76 * a30);
    a84 = (a6 * a32);
    a83 = (a83 + a84);
    a84 = (a0 * a33);
    a83 = (a83 + a84);
    a82 = (a82 - a83);
    a82 = (a2 * a82);
    a83 = (a82 / a7);
    a83 = (a23 + a83);
    a84 = (a31 * a71);
    a67 = (a67 / a7);
    a85 = (a67 / a28);
    a84 = (a84 + a85);
    a85 = (a70 * a30);
    a86 = (a72 * a32);
    a85 = (a85 + a86);
    a86 = (a73 * a33);
    a85 = (a85 + a86);
    a84 = (a84 - a85);
    a84 = (a2 * a84);
    a85 = (a84 / a7);
    a85 = (a28 + a85);
    a86 = (a83 / a85);
    a86 = (a86 / a77);
    a87 = (a39 * a71);
    a88 = (a66 / a28);
    a87 = (a87 - a88);
    a87 = (a2 * a87);
    a88 = (a87 / a7);
    a88 = (a30 + a88);
    a89 = (a20 * a88);
    a90 = (a51 * a71);
    a91 = (a52 * a31);
    a92 = (a68 * a54);
    a93 = (a72 * a50);
    a94 = (a73 * a55);
    a93 = (a93 + a94);
    a92 = (a92 - a93);
    a91 = (a91 - a92);
    a92 = (a56 * a29);
    a91 = (a91 - a92);
    a92 = (a49 * a66);
    a91 = (a91 + a92);
    a91 = (a91 * a50);
    a92 = (a91 / a28);
    a90 = (a90 - a92);
    a90 = (a2 * a90);
    a92 = (a90 / a7);
    a92 = (a32 + a92);
    a93 = (a27 * a92);
    a89 = (a89 + a93);
    a93 = (a60 * a71);
    a94 = (a35 * a31);
    a95 = (a68 * a62);
    a96 = (a73 * a59);
    a95 = (a95 - a96);
    a94 = (a94 - a95);
    a95 = (a63 * a29);
    a94 = (a94 - a95);
    a95 = (a64 * a66);
    a94 = (a94 - a95);
    a95 = (a58 * a91);
    a94 = (a94 + a95);
    a94 = (a94 * a59);
    a95 = (a94 / a28);
    a93 = (a93 - a95);
    a93 = (a2 * a93);
    a95 = (a93 / a7);
    a95 = (a33 + a95);
    a96 = (a4 * a95);
    a89 = (a89 + a96);
    a96 = (a70 * a9);
    a97 = (a72 * a3);
    a96 = (a96 + a97);
    a97 = (a73 * a13);
    a96 = (a96 + a97);
    a31 = (a31 / a15);
    a96 = (a96 + a31);
    a96 = (a2 * a96);
    a31 = (a96 / a7);
    a31 = (a34 - a31);
    a97 = (a31 / a12);
    a97 = (a97 / a85);
    a98 = (a11 * a97);
    a89 = (a89 + a98);
    a89 = (a89 * a85);
    a98 = (a86 * a89);
    a99 = (a83 * a97);
    a100 = (a76 * a9);
    a101 = (a6 * a3);
    a100 = (a100 + a101);
    a101 = (a0 * a13);
    a100 = (a100 + a101);
    a101 = (a36 / a15);
    a100 = (a100 + a101);
    a100 = (a2 * a100);
    a101 = (a100 / a7);
    a101 = (a38 - a101);
    a102 = (a101 / a12);
    a99 = (a99 - a102);
    a99 = (a99 / a77);
    a102 = (a11 * a99);
    a103 = (a20 * a44);
    a104 = (a91 * a37);
    a105 = (a51 * a74);
    a104 = (a104 - a105);
    a105 = (a52 * a36);
    a106 = (a75 * a56);
    a107 = (a6 * a50);
    a108 = (a0 * a55);
    a107 = (a107 + a108);
    a106 = (a106 - a107);
    a105 = (a105 - a106);
    a106 = (a54 * a29);
    a105 = (a105 + a106);
    a106 = (a49 * a19);
    a105 = (a105 + a106);
    a105 = (a105 * a50);
    a106 = (a105 / a24);
    a104 = (a104 - a106);
    a104 = (a2 * a104);
    a106 = (a104 / a7);
    a106 = (a41 + a106);
    a107 = (a27 * a106);
    a103 = (a103 + a107);
    a107 = (a94 * a37);
    a108 = (a60 * a74);
    a107 = (a107 - a108);
    a36 = (a35 * a36);
    a108 = (a75 * a63);
    a109 = (a0 * a59);
    a108 = (a108 - a109);
    a36 = (a36 - a108);
    a29 = (a62 * a29);
    a36 = (a36 + a29);
    a29 = (a64 * a19);
    a36 = (a36 - a29);
    a29 = (a58 * a105);
    a36 = (a36 + a29);
    a36 = (a36 * a59);
    a29 = (a36 / a24);
    a107 = (a107 - a29);
    a107 = (a2 * a107);
    a29 = (a107 / a7);
    a29 = (a42 + a29);
    a108 = (a4 * a29);
    a103 = (a103 + a108);
    a102 = (a102 - a103);
    a98 = (a98 - a102);
    a98 = (a98 * a77);
    a102 = (a25 * a98);
    a103 = (a88 * a97);
    a108 = (a47 / a12);
    a103 = (a103 - a108);
    a108 = (a44 * a99);
    a103 = (a103 - a108);
    a103 = (a103 / a81);
    a108 = (a11 * a103);
    a109 = (a20 * a81);
    a110 = (a105 * a17);
    a111 = (a51 * a1);
    a112 = (a91 * a78);
    a111 = (a111 + a112);
    a110 = (a110 - a111);
    a79 = (a79 / a7);
    a49 = (a79 * a49);
    a52 = (a52 * a39);
    a49 = (a49 + a52);
    a54 = (a54 * a66);
    a49 = (a49 + a54);
    a56 = (a56 * a19);
    a49 = (a49 + a56);
    a49 = (a49 * a50);
    a56 = (a49 / a26);
    a110 = (a110 - a56);
    a110 = (a2 * a110);
    a56 = (a110 / a7);
    a56 = (a45 + a56);
    a54 = (a27 * a56);
    a109 = (a109 + a54);
    a54 = (a36 * a17);
    a52 = (a60 * a1);
    a111 = (a94 * a78);
    a52 = (a52 + a111);
    a54 = (a54 - a52);
    a39 = (a35 * a39);
    a52 = (a79 * a64);
    a39 = (a39 - a52);
    a66 = (a62 * a66);
    a39 = (a39 + a66);
    a19 = (a63 * a19);
    a39 = (a39 + a19);
    a19 = (a58 * a49);
    a39 = (a39 + a19);
    a39 = (a39 * a59);
    a19 = (a39 / a26);
    a54 = (a54 - a19);
    a54 = (a2 * a54);
    a19 = (a54 / a7);
    a19 = (a46 + a19);
    a66 = (a4 * a19);
    a109 = (a109 + a66);
    a108 = (a108 - a109);
    a109 = (a44 * a86);
    a66 = (a88 / a85);
    a109 = (a109 - a66);
    a109 = (a109 / a81);
    a66 = (a109 * a89);
    a108 = (a108 + a66);
    a102 = (a102 - a108);
    a102 = (a102 * a81);
    a108 = (a102 / a12);
    a108 = (a2 * a108);
    a66 = (a108 / a7);
    a66 = (a9 - a66);
    a52 = (a20 * a66);
    a111 = (a56 / a81);
    a112 = (a45 / a26);
    a112 = (a112 / a50);
    a113 = (a49 * a112);
    a114 = (a32 * a71);
    a115 = (a3 / a15);
    a114 = (a114 - a115);
    a115 = (a41 * a74);
    a114 = (a114 - a115);
    a115 = (a45 * a1);
    a114 = (a114 - a115);
    a114 = (a114 / a50);
    a115 = (a51 * a114);
    a116 = (a41 * a37);
    a117 = (a32 / a28);
    a116 = (a116 - a117);
    a117 = (a45 * a78);
    a116 = (a116 - a117);
    a116 = (a116 / a50);
    a117 = (a91 * a116);
    a115 = (a115 + a117);
    a117 = (a45 * a17);
    a118 = (a41 / a24);
    a117 = (a117 - a118);
    a117 = (a117 / a50);
    a118 = (a105 * a117);
    a115 = (a115 + a118);
    a113 = (a113 - a115);
    a115 = casadi_sq(a22);
    a118 = (a115 / a7);
    a119 = (a118 / a50);
    a113 = (a113 + a119);
    a113 = (a2 * a113);
    a119 = (a113 / a7);
    a119 = (a50 + a119);
    a111 = (a111 / a119);
    a120 = (a111 * a102);
    a121 = (a92 * a97);
    a122 = (a57 / a12);
    a121 = (a121 - a122);
    a122 = (a106 * a99);
    a121 = (a121 - a122);
    a122 = (a56 * a103);
    a121 = (a121 - a122);
    a121 = (a121 / a119);
    a122 = (a11 * a121);
    a123 = (a27 * a119);
    a124 = (a39 * a112);
    a125 = (a60 * a114);
    a126 = (a94 * a116);
    a125 = (a125 + a126);
    a126 = (a36 * a117);
    a125 = (a125 + a126);
    a124 = (a124 - a125);
    a115 = (a115 / a7);
    a58 = (a115 * a58);
    a35 = (a35 * a51);
    a58 = (a58 + a35);
    a62 = (a62 * a91);
    a58 = (a58 + a62);
    a63 = (a63 * a105);
    a58 = (a58 + a63);
    a64 = (a64 * a49);
    a58 = (a58 + a64);
    a58 = (a58 * a59);
    a64 = (a58 / a50);
    a124 = (a124 - a64);
    a124 = (a2 * a124);
    a64 = (a124 / a7);
    a64 = (a55 + a64);
    a49 = (a4 * a64);
    a123 = (a123 + a49);
    a122 = (a122 - a123);
    a123 = (a106 * a86);
    a49 = (a92 / a85);
    a123 = (a123 - a49);
    a49 = (a56 * a109);
    a123 = (a123 - a49);
    a123 = (a123 / a119);
    a49 = (a123 * a89);
    a122 = (a122 + a49);
    a49 = (a56 * a25);
    a63 = (a106 / a77);
    a49 = (a49 - a63);
    a49 = (a49 / a119);
    a63 = (a49 * a98);
    a122 = (a122 + a63);
    a120 = (a120 - a122);
    a120 = (a120 * a119);
    a122 = (a120 / a12);
    a122 = (a2 * a122);
    a63 = (a122 / a7);
    a63 = (a3 - a63);
    a105 = (a27 * a63);
    a52 = (a52 + a105);
    a105 = (a64 / a119);
    a62 = (a55 / a50);
    a62 = (a62 / a59);
    a58 = (a58 * a62);
    a71 = (a33 * a71);
    a62 = (a13 / a15);
    a71 = (a71 - a62);
    a74 = (a42 * a74);
    a71 = (a71 - a74);
    a1 = (a46 * a1);
    a71 = (a71 - a1);
    a114 = (a55 * a114);
    a71 = (a71 - a114);
    a71 = (a71 / a59);
    a60 = (a60 * a71);
    a37 = (a42 * a37);
    a71 = (a33 / a28);
    a37 = (a37 - a71);
    a78 = (a46 * a78);
    a37 = (a37 - a78);
    a116 = (a55 * a116);
    a37 = (a37 - a116);
    a37 = (a37 / a59);
    a94 = (a94 * a37);
    a60 = (a60 + a94);
    a17 = (a46 * a17);
    a94 = (a42 / a24);
    a17 = (a17 - a94);
    a117 = (a55 * a117);
    a17 = (a17 - a117);
    a17 = (a17 / a59);
    a36 = (a36 * a17);
    a60 = (a60 + a36);
    a112 = (a55 * a112);
    a36 = (a46 / a26);
    a112 = (a112 - a36);
    a112 = (a112 / a59);
    a39 = (a39 * a112);
    a60 = (a60 + a39);
    a58 = (a58 - a60);
    a22 = casadi_sq(a22);
    a22 = (a22 / a7);
    a60 = (a22 / a59);
    a58 = (a58 + a60);
    a58 = (a2 * a58);
    a60 = (a58 / a7);
    a60 = (a59 + a60);
    a105 = (a105 / a60);
    a39 = (a105 * a120);
    a97 = (a95 * a97);
    a112 = (a65 / a12);
    a97 = (a97 - a112);
    a112 = (a29 * a99);
    a97 = (a97 - a112);
    a112 = (a19 * a103);
    a97 = (a97 - a112);
    a112 = (a64 * a121);
    a97 = (a97 - a112);
    a97 = (a97 / a60);
    a112 = (a11 * a97);
    a36 = (a4 * a60);
    a112 = (a112 - a36);
    a36 = (a29 * a86);
    a17 = (a95 / a85);
    a36 = (a36 - a17);
    a17 = (a19 * a109);
    a36 = (a36 - a17);
    a17 = (a64 * a123);
    a36 = (a36 - a17);
    a36 = (a36 / a60);
    a17 = (a36 * a89);
    a112 = (a112 + a17);
    a17 = (a19 * a25);
    a117 = (a29 / a77);
    a17 = (a17 - a117);
    a117 = (a64 * a49);
    a17 = (a17 - a117);
    a17 = (a17 / a60);
    a117 = (a17 * a98);
    a112 = (a112 + a117);
    a117 = (a64 * a111);
    a94 = (a19 / a81);
    a117 = (a117 - a94);
    a117 = (a117 / a60);
    a94 = (a117 * a102);
    a112 = (a112 + a94);
    a39 = (a39 - a112);
    a39 = (a39 * a60);
    a112 = (a39 / a12);
    a112 = (a2 * a112);
    a94 = (a112 / a7);
    a94 = (a13 - a94);
    a37 = (a4 * a94);
    a52 = (a52 + a37);
    a48 = (a48 - a52);
    a48 = (a2 * a48);
    a52 = (a7 * a48);
    a8 = (a8 + a52);
    a48 = (a15 + a48);
    a21 = (a21 / a48);
    a52 = (a103 * a89);
    a37 = (a68 * a109);
    a116 = (a70 * a81);
    a78 = (a72 * a56);
    a116 = (a116 + a78);
    a78 = (a73 * a19);
    a116 = (a116 + a78);
    a37 = (a37 - a116);
    a52 = (a52 - a37);
    a86 = (a68 * a86);
    a37 = (a70 * a44);
    a116 = (a72 * a106);
    a37 = (a37 + a116);
    a116 = (a73 * a29);
    a37 = (a37 + a116);
    a86 = (a86 + a37);
    a99 = (a99 * a89);
    a86 = (a86 + a99);
    a86 = (a86 * a77);
    a99 = (a25 * a86);
    a52 = (a52 + a99);
    a52 = (a52 * a81);
    a99 = (a83 / a85);
    a99 = (a99 / a77);
    a37 = (a52 * a99);
    a31 = (a31 / a12);
    a31 = (a31 / a85);
    a83 = (a83 * a31);
    a101 = (a101 / a12);
    a83 = (a83 - a101);
    a83 = (a83 / a77);
    a101 = (a102 * a83);
    a37 = (a37 - a101);
    a25 = (a75 * a25);
    a101 = (a76 * a81);
    a116 = (a6 * a56);
    a101 = (a101 + a116);
    a116 = (a0 * a19);
    a101 = (a101 + a116);
    a25 = (a25 + a101);
    a103 = (a103 * a98);
    a25 = (a25 + a103);
    a109 = (a109 * a86);
    a25 = (a25 + a109);
    a25 = (a25 * a81);
    a109 = (a25 / a77);
    a37 = (a37 - a109);
    a37 = (a2 * a37);
    a109 = (a37 / a7);
    a109 = (a10 + a109);
    a103 = (a86 * a99);
    a101 = (a98 * a83);
    a103 = (a103 - a101);
    a101 = (a14 / a77);
    a103 = (a103 + a101);
    a101 = (a76 * a44);
    a116 = (a6 * a106);
    a101 = (a101 + a116);
    a116 = (a0 * a29);
    a101 = (a101 + a116);
    a103 = (a103 - a101);
    a103 = (a2 * a103);
    a101 = (a103 / a7);
    a101 = (a24 + a101);
    a116 = (a109 / a101);
    a78 = (a44 / a77);
    a78 = (a78 / a81);
    a71 = (a25 * a78);
    a114 = (a88 * a31);
    a1 = (a47 / a12);
    a114 = (a114 - a1);
    a1 = (a44 * a83);
    a114 = (a114 - a1);
    a114 = (a114 / a81);
    a1 = (a102 * a114);
    a44 = (a44 * a99);
    a74 = (a88 / a85);
    a44 = (a44 - a74);
    a44 = (a44 / a81);
    a74 = (a52 * a44);
    a1 = (a1 + a74);
    a71 = (a71 - a1);
    a1 = (a80 / a81);
    a71 = (a71 + a1);
    a71 = (a2 * a71);
    a1 = (a71 / a7);
    a1 = (a26 + a1);
    a116 = (a116 / a1);
    a74 = (a98 * a31);
    a62 = (a86 / a85);
    a74 = (a74 - a62);
    a62 = (a76 * a88);
    a91 = (a6 * a92);
    a62 = (a62 + a91);
    a91 = (a0 * a95);
    a62 = (a62 + a91);
    a74 = (a74 - a62);
    a74 = (a2 * a74);
    a62 = (a74 / a7);
    a62 = (a23 + a62);
    a91 = (a89 * a31);
    a35 = (a67 / a85);
    a91 = (a91 + a35);
    a88 = (a70 * a88);
    a35 = (a72 * a92);
    a88 = (a88 + a35);
    a35 = (a73 * a95);
    a88 = (a88 + a35);
    a91 = (a91 - a88);
    a91 = (a2 * a91);
    a88 = (a91 / a7);
    a88 = (a28 + a88);
    a35 = (a62 / a88);
    a35 = (a35 / a101);
    a51 = (a102 * a31);
    a125 = (a52 / a85);
    a51 = (a51 - a125);
    a51 = (a2 * a51);
    a125 = (a51 / a7);
    a125 = (a30 + a125);
    a126 = (a20 * a125);
    a127 = (a120 * a31);
    a128 = (a121 * a89);
    a129 = (a68 * a123);
    a130 = (a72 * a119);
    a131 = (a73 * a64);
    a130 = (a130 + a131);
    a129 = (a129 - a130);
    a128 = (a128 - a129);
    a129 = (a49 * a86);
    a128 = (a128 - a129);
    a129 = (a111 * a52);
    a128 = (a128 + a129);
    a128 = (a128 * a119);
    a129 = (a128 / a85);
    a127 = (a127 - a129);
    a127 = (a2 * a127);
    a129 = (a127 / a7);
    a129 = (a32 + a129);
    a130 = (a27 * a129);
    a126 = (a126 + a130);
    a130 = (a39 * a31);
    a131 = (a97 * a89);
    a132 = (a68 * a36);
    a133 = (a73 * a60);
    a132 = (a132 - a133);
    a131 = (a131 - a132);
    a132 = (a17 * a86);
    a131 = (a131 - a132);
    a132 = (a117 * a52);
    a131 = (a131 - a132);
    a132 = (a105 * a128);
    a131 = (a131 + a132);
    a131 = (a131 * a60);
    a132 = (a131 / a85);
    a130 = (a130 - a132);
    a130 = (a2 * a130);
    a132 = (a130 / a7);
    a132 = (a33 + a132);
    a133 = (a4 * a132);
    a126 = (a126 + a133);
    a133 = (a70 * a47);
    a134 = (a72 * a57);
    a133 = (a133 + a134);
    a134 = (a73 * a65);
    a133 = (a133 + a134);
    a89 = (a89 / a12);
    a133 = (a133 + a89);
    a133 = (a2 * a133);
    a89 = (a133 / a7);
    a89 = (a34 - a89);
    a134 = (a89 / a18);
    a134 = (a134 / a88);
    a135 = (a11 * a134);
    a126 = (a126 + a135);
    a126 = (a126 * a88);
    a135 = (a35 * a126);
    a136 = (a62 * a134);
    a47 = (a76 * a47);
    a137 = (a6 * a57);
    a47 = (a47 + a137);
    a137 = (a0 * a65);
    a47 = (a47 + a137);
    a137 = (a98 / a12);
    a47 = (a47 + a137);
    a47 = (a2 * a47);
    a137 = (a47 / a7);
    a137 = (a38 - a137);
    a138 = (a137 / a18);
    a136 = (a136 - a138);
    a136 = (a136 / a101);
    a138 = (a11 * a136);
    a139 = (a20 * a109);
    a140 = (a128 * a99);
    a141 = (a120 * a83);
    a140 = (a140 - a141);
    a141 = (a121 * a98);
    a142 = (a75 * a49);
    a143 = (a6 * a119);
    a144 = (a0 * a64);
    a143 = (a143 + a144);
    a142 = (a142 - a143);
    a141 = (a141 - a142);
    a142 = (a123 * a86);
    a141 = (a141 + a142);
    a142 = (a111 * a25);
    a141 = (a141 + a142);
    a141 = (a141 * a119);
    a142 = (a141 / a77);
    a140 = (a140 - a142);
    a140 = (a2 * a140);
    a142 = (a140 / a7);
    a142 = (a41 + a142);
    a143 = (a27 * a142);
    a139 = (a139 + a143);
    a143 = (a131 * a99);
    a144 = (a39 * a83);
    a143 = (a143 - a144);
    a98 = (a97 * a98);
    a144 = (a75 * a17);
    a145 = (a0 * a60);
    a144 = (a144 - a145);
    a98 = (a98 - a144);
    a86 = (a36 * a86);
    a98 = (a98 + a86);
    a86 = (a117 * a25);
    a98 = (a98 - a86);
    a86 = (a105 * a141);
    a98 = (a98 + a86);
    a98 = (a98 * a60);
    a86 = (a98 / a77);
    a143 = (a143 - a86);
    a143 = (a2 * a143);
    a86 = (a143 / a7);
    a86 = (a42 + a86);
    a144 = (a4 * a86);
    a139 = (a139 + a144);
    a138 = (a138 - a139);
    a135 = (a135 - a138);
    a135 = (a135 * a101);
    a138 = (a116 * a135);
    a139 = (a125 * a134);
    a144 = (a66 / a18);
    a139 = (a139 - a144);
    a144 = (a109 * a136);
    a139 = (a139 - a144);
    a139 = (a139 / a1);
    a144 = (a11 * a139);
    a145 = (a20 * a1);
    a146 = (a141 * a78);
    a147 = (a120 * a114);
    a148 = (a128 * a44);
    a147 = (a147 + a148);
    a146 = (a146 - a147);
    a111 = (a79 * a111);
    a121 = (a121 * a102);
    a111 = (a111 + a121);
    a123 = (a123 * a52);
    a111 = (a111 + a123);
    a49 = (a49 * a25);
    a111 = (a111 + a49);
    a111 = (a111 * a119);
    a49 = (a111 / a81);
    a146 = (a146 - a49);
    a146 = (a2 * a146);
    a49 = (a146 / a7);
    a49 = (a45 + a49);
    a123 = (a27 * a49);
    a145 = (a145 + a123);
    a123 = (a98 * a78);
    a121 = (a39 * a114);
    a147 = (a131 * a44);
    a121 = (a121 + a147);
    a123 = (a123 - a121);
    a102 = (a97 * a102);
    a121 = (a79 * a117);
    a102 = (a102 - a121);
    a52 = (a36 * a52);
    a102 = (a102 + a52);
    a25 = (a17 * a25);
    a102 = (a102 + a25);
    a25 = (a105 * a111);
    a102 = (a102 + a25);
    a102 = (a102 * a60);
    a25 = (a102 / a81);
    a123 = (a123 - a25);
    a123 = (a2 * a123);
    a25 = (a123 / a7);
    a25 = (a46 + a25);
    a52 = (a4 * a25);
    a145 = (a145 + a52);
    a144 = (a144 - a145);
    a145 = (a109 * a35);
    a52 = (a125 / a88);
    a145 = (a145 - a52);
    a145 = (a145 / a1);
    a52 = (a145 * a126);
    a144 = (a144 + a52);
    a138 = (a138 - a144);
    a138 = (a138 * a1);
    a144 = (a138 / a18);
    a144 = (a2 * a144);
    a52 = (a9 - a144);
    a121 = (a20 * a52);
    a147 = (a49 / a1);
    a148 = (a56 / a81);
    a148 = (a148 / a119);
    a149 = (a111 * a148);
    a150 = (a92 * a31);
    a57 = (a57 / a12);
    a150 = (a150 - a57);
    a57 = (a106 * a83);
    a150 = (a150 - a57);
    a57 = (a56 * a114);
    a150 = (a150 - a57);
    a150 = (a150 / a119);
    a57 = (a120 * a150);
    a151 = (a106 * a99);
    a92 = (a92 / a85);
    a151 = (a151 - a92);
    a92 = (a56 * a44);
    a151 = (a151 - a92);
    a151 = (a151 / a119);
    a92 = (a128 * a151);
    a57 = (a57 + a92);
    a56 = (a56 * a78);
    a106 = (a106 / a77);
    a56 = (a56 - a106);
    a56 = (a56 / a119);
    a106 = (a141 * a56);
    a57 = (a57 + a106);
    a149 = (a149 - a57);
    a57 = (a118 / a119);
    a149 = (a149 + a57);
    a149 = (a2 * a149);
    a57 = (a149 / a7);
    a57 = (a50 + a57);
    a147 = (a147 / a57);
    a106 = (a147 * a138);
    a92 = (a129 * a134);
    a152 = (a63 / a18);
    a92 = (a92 - a152);
    a152 = (a142 * a136);
    a92 = (a92 - a152);
    a152 = (a49 * a139);
    a92 = (a92 - a152);
    a92 = (a92 / a57);
    a152 = (a11 * a92);
    a153 = (a27 * a57);
    a154 = (a102 * a148);
    a155 = (a39 * a150);
    a156 = (a131 * a151);
    a155 = (a155 + a156);
    a156 = (a98 * a56);
    a155 = (a155 + a156);
    a154 = (a154 - a155);
    a105 = (a115 * a105);
    a97 = (a97 * a120);
    a105 = (a105 + a97);
    a36 = (a36 * a128);
    a105 = (a105 + a36);
    a17 = (a17 * a141);
    a105 = (a105 + a17);
    a117 = (a117 * a111);
    a105 = (a105 + a117);
    a105 = (a105 * a60);
    a117 = (a105 / a119);
    a154 = (a154 - a117);
    a154 = (a2 * a154);
    a117 = (a154 / a7);
    a117 = (a55 + a117);
    a111 = (a4 * a117);
    a153 = (a153 + a111);
    a152 = (a152 - a153);
    a153 = (a142 * a35);
    a111 = (a129 / a88);
    a153 = (a153 - a111);
    a111 = (a49 * a145);
    a153 = (a153 - a111);
    a153 = (a153 / a57);
    a111 = (a153 * a126);
    a152 = (a152 + a111);
    a111 = (a49 * a116);
    a17 = (a142 / a101);
    a111 = (a111 - a17);
    a111 = (a111 / a57);
    a17 = (a111 * a135);
    a152 = (a152 + a17);
    a106 = (a106 - a152);
    a106 = (a106 * a57);
    a152 = (a106 / a18);
    a152 = (a2 * a152);
    a17 = (a3 - a152);
    a141 = (a27 * a17);
    a121 = (a121 + a141);
    a141 = (a117 / a57);
    a119 = (a64 / a119);
    a119 = (a119 / a60);
    a105 = (a105 * a119);
    a31 = (a95 * a31);
    a65 = (a65 / a12);
    a31 = (a31 - a65);
    a83 = (a29 * a83);
    a31 = (a31 - a83);
    a114 = (a19 * a114);
    a31 = (a31 - a114);
    a150 = (a64 * a150);
    a31 = (a31 - a150);
    a31 = (a31 / a60);
    a39 = (a39 * a31);
    a99 = (a29 * a99);
    a95 = (a95 / a85);
    a99 = (a99 - a95);
    a44 = (a19 * a44);
    a99 = (a99 - a44);
    a151 = (a64 * a151);
    a99 = (a99 - a151);
    a99 = (a99 / a60);
    a131 = (a131 * a99);
    a39 = (a39 + a131);
    a78 = (a19 * a78);
    a29 = (a29 / a77);
    a78 = (a78 - a29);
    a56 = (a64 * a56);
    a78 = (a78 - a56);
    a78 = (a78 / a60);
    a98 = (a98 * a78);
    a39 = (a39 + a98);
    a64 = (a64 * a148);
    a19 = (a19 / a81);
    a64 = (a64 - a19);
    a64 = (a64 / a60);
    a102 = (a102 * a64);
    a39 = (a39 + a102);
    a105 = (a105 - a39);
    a60 = (a22 / a60);
    a105 = (a105 + a60);
    a105 = (a2 * a105);
    a60 = (a105 / a7);
    a60 = (a59 + a60);
    a141 = (a141 / a60);
    a39 = (a141 * a106);
    a134 = (a132 * a134);
    a102 = (a94 / a18);
    a134 = (a134 - a102);
    a102 = (a86 * a136);
    a134 = (a134 - a102);
    a102 = (a25 * a139);
    a134 = (a134 - a102);
    a102 = (a117 * a92);
    a134 = (a134 - a102);
    a134 = (a134 / a60);
    a102 = (a11 * a134);
    a64 = (a4 * a60);
    a102 = (a102 - a64);
    a64 = (a86 * a35);
    a19 = (a132 / a88);
    a64 = (a64 - a19);
    a19 = (a25 * a145);
    a64 = (a64 - a19);
    a19 = (a117 * a153);
    a64 = (a64 - a19);
    a64 = (a64 / a60);
    a19 = (a64 * a126);
    a102 = (a102 + a19);
    a19 = (a25 * a116);
    a81 = (a86 / a101);
    a19 = (a19 - a81);
    a81 = (a117 * a111);
    a19 = (a19 - a81);
    a19 = (a19 / a60);
    a81 = (a19 * a135);
    a102 = (a102 + a81);
    a81 = (a117 * a147);
    a148 = (a25 / a1);
    a81 = (a81 - a148);
    a81 = (a81 / a60);
    a148 = (a81 * a138);
    a102 = (a102 + a148);
    a39 = (a39 - a102);
    a39 = (a39 * a60);
    a102 = (a39 / a18);
    a102 = (a2 * a102);
    a148 = (a13 - a102);
    a98 = (a4 * a148);
    a121 = (a121 + a98);
    a21 = (a21 - a121);
    a21 = (a2 * a21);
    a8 = (a8 + a21);
    a8 = (a8 / a16);
    a15 = (a15 + a8);
    if (res[1] != 0)
        res[1][0] = a15;
    a133 = (a7 * a133);
    a96 = (a96 + a133);
    a133 = (a70 * a66);
    a15 = (a72 * a63);
    a133 = (a133 + a15);
    a15 = (a73 * a94);
    a133 = (a133 + a15);
    a15 = (a126 / a18);
    a133 = (a133 + a15);
    a133 = (a2 * a133);
    a15 = (a7 * a133);
    a96 = (a96 + a15);
    a15 = (a70 * a52);
    a8 = (a72 * a17);
    a15 = (a15 + a8);
    a8 = (a73 * a148);
    a15 = (a15 + a8);
    a89 = (a89 / a18);
    a89 = (a89 / a88);
    a8 = (a138 * a89);
    a21 = (a139 * a126);
    a121 = (a68 * a145);
    a98 = (a70 * a1);
    a78 = (a72 * a49);
    a98 = (a98 + a78);
    a78 = (a73 * a25);
    a98 = (a98 + a78);
    a121 = (a121 - a98);
    a21 = (a21 - a121);
    a35 = (a68 * a35);
    a121 = (a70 * a109);
    a98 = (a72 * a142);
    a121 = (a121 + a98);
    a98 = (a73 * a86);
    a121 = (a121 + a98);
    a35 = (a35 + a121);
    a136 = (a136 * a126);
    a35 = (a35 + a136);
    a35 = (a35 * a101);
    a136 = (a116 * a35);
    a21 = (a21 + a136);
    a21 = (a21 * a1);
    a136 = (a21 / a88);
    a8 = (a8 - a136);
    a8 = (a2 * a8);
    a136 = (a30 + a8);
    a121 = (a20 * a136);
    a98 = (a106 * a89);
    a78 = (a92 * a126);
    a56 = (a68 * a153);
    a29 = (a72 * a57);
    a77 = (a73 * a117);
    a29 = (a29 + a77);
    a56 = (a56 - a29);
    a78 = (a78 - a56);
    a56 = (a111 * a35);
    a78 = (a78 - a56);
    a56 = (a147 * a21);
    a78 = (a78 + a56);
    a78 = (a78 * a57);
    a56 = (a78 / a88);
    a98 = (a98 - a56);
    a98 = (a2 * a98);
    a56 = (a32 + a98);
    a29 = (a27 * a56);
    a121 = (a121 + a29);
    a29 = (a39 * a89);
    a77 = (a134 * a126);
    a131 = (a68 * a64);
    a99 = (a73 * a60);
    a131 = (a131 - a99);
    a77 = (a77 - a131);
    a131 = (a19 * a35);
    a77 = (a77 - a131);
    a131 = (a81 * a21);
    a77 = (a77 - a131);
    a131 = (a141 * a78);
    a77 = (a77 + a131);
    a77 = (a77 * a60);
    a131 = (a77 / a88);
    a29 = (a29 - a131);
    a29 = (a2 * a29);
    a131 = (a33 + a29);
    a99 = (a4 * a131);
    a121 = (a121 + a99);
    a133 = (a34 - a133);
    a99 = (a133 / a48);
    a126 = (a126 * a89);
    a151 = (a67 / a88);
    a126 = (a126 + a151);
    a151 = (a70 * a125);
    a44 = (a72 * a129);
    a151 = (a151 + a44);
    a44 = (a73 * a132);
    a151 = (a151 + a44);
    a126 = (a126 - a151);
    a126 = (a2 * a126);
    a151 = (a28 + a126);
    a99 = (a99 / a151);
    a44 = (a11 * a99);
    a121 = (a121 + a44);
    a121 = (a121 * a151);
    a44 = (a121 / a48);
    a15 = (a15 + a44);
    a15 = (a2 * a15);
    a96 = (a96 + a15);
    a96 = (a96 / a16);
    a34 = (a34 - a96);
    if (res[1] != 0)
        res[1][1] = a34;
    a47 = (a7 * a47);
    a100 = (a100 + a47);
    a47 = (a76 * a66);
    a34 = (a6 * a63);
    a47 = (a47 + a34);
    a34 = (a0 * a94);
    a47 = (a47 + a34);
    a34 = (a135 / a18);
    a47 = (a47 + a34);
    a47 = (a2 * a47);
    a34 = (a7 * a47);
    a100 = (a100 + a34);
    a34 = (a76 * a52);
    a96 = (a6 * a17);
    a34 = (a34 + a96);
    a96 = (a0 * a148);
    a34 = (a34 + a96);
    a96 = (a135 * a89);
    a15 = (a35 / a88);
    a96 = (a96 - a15);
    a15 = (a76 * a125);
    a44 = (a6 * a129);
    a15 = (a15 + a44);
    a44 = (a0 * a132);
    a15 = (a15 + a44);
    a96 = (a96 - a15);
    a96 = (a2 * a96);
    a15 = (a23 + a96);
    a44 = (a15 / a151);
    a95 = (a62 / a88);
    a95 = (a95 / a101);
    a85 = (a35 * a95);
    a62 = (a62 * a89);
    a137 = (a137 / a18);
    a62 = (a62 - a137);
    a62 = (a62 / a101);
    a137 = (a135 * a62);
    a85 = (a85 - a137);
    a137 = (a14 / a101);
    a85 = (a85 + a137);
    a137 = (a76 * a109);
    a31 = (a6 * a142);
    a137 = (a137 + a31);
    a31 = (a0 * a86);
    a137 = (a137 + a31);
    a85 = (a85 - a137);
    a85 = (a2 * a85);
    a137 = (a24 + a85);
    a44 = (a44 / a137);
    a31 = (a44 * a121);
    a150 = (a15 * a99);
    a47 = (a38 - a47);
    a114 = (a47 / a48);
    a150 = (a150 - a114);
    a150 = (a150 / a137);
    a114 = (a11 * a150);
    a83 = (a21 * a95);
    a65 = (a138 * a62);
    a83 = (a83 - a65);
    a116 = (a75 * a116);
    a65 = (a76 * a1);
    a12 = (a6 * a49);
    a65 = (a65 + a12);
    a12 = (a0 * a25);
    a65 = (a65 + a12);
    a116 = (a116 + a65);
    a139 = (a139 * a135);
    a116 = (a116 + a139);
    a145 = (a145 * a35);
    a116 = (a116 + a145);
    a116 = (a116 * a1);
    a145 = (a116 / a101);
    a83 = (a83 - a145);
    a83 = (a2 * a83);
    a145 = (a10 + a83);
    a139 = (a20 * a145);
    a65 = (a78 * a95);
    a12 = (a106 * a62);
    a65 = (a65 - a12);
    a12 = (a92 * a135);
    a119 = (a75 * a111);
    a36 = (a6 * a57);
    a128 = (a0 * a117);
    a36 = (a36 + a128);
    a119 = (a119 - a36);
    a12 = (a12 - a119);
    a119 = (a153 * a35);
    a12 = (a12 + a119);
    a119 = (a147 * a116);
    a12 = (a12 + a119);
    a12 = (a12 * a57);
    a119 = (a12 / a101);
    a65 = (a65 - a119);
    a65 = (a2 * a65);
    a119 = (a41 + a65);
    a36 = (a27 * a119);
    a139 = (a139 + a36);
    a36 = (a77 * a95);
    a128 = (a39 * a62);
    a36 = (a36 - a128);
    a135 = (a134 * a135);
    a128 = (a75 * a19);
    a97 = (a0 * a60);
    a128 = (a128 - a97);
    a135 = (a135 - a128);
    a35 = (a64 * a35);
    a135 = (a135 + a35);
    a35 = (a81 * a116);
    a135 = (a135 - a35);
    a35 = (a141 * a12);
    a135 = (a135 + a35);
    a135 = (a135 * a60);
    a35 = (a135 / a101);
    a36 = (a36 - a35);
    a36 = (a2 * a36);
    a35 = (a42 + a36);
    a128 = (a4 * a35);
    a139 = (a139 + a128);
    a114 = (a114 - a139);
    a31 = (a31 - a114);
    a31 = (a31 * a137);
    a114 = (a31 / a48);
    a34 = (a34 + a114);
    a34 = (a2 * a34);
    a100 = (a100 + a34);
    a100 = (a100 / a16);
    a38 = (a38 - a100);
    if (res[1] != 0)
        res[1][2] = a38;
    a108 = (a7 * a108);
    a43 = (a43 + a108);
    a144 = (a7 * a144);
    a43 = (a43 + a144);
    a144 = (a145 / a137);
    a108 = (a109 / a101);
    a108 = (a108 / a1);
    a38 = (a116 * a108);
    a100 = (a125 * a89);
    a66 = (a66 / a18);
    a100 = (a100 - a66);
    a66 = (a109 * a62);
    a100 = (a100 - a66);
    a100 = (a100 / a1);
    a66 = (a138 * a100);
    a109 = (a109 * a95);
    a125 = (a125 / a88);
    a109 = (a109 - a125);
    a109 = (a109 / a1);
    a125 = (a21 * a109);
    a66 = (a66 + a125);
    a38 = (a38 - a66);
    a66 = (a80 / a1);
    a38 = (a38 + a66);
    a38 = (a2 * a38);
    a66 = (a26 + a38);
    a144 = (a144 / a66);
    a125 = (a144 * a31);
    a34 = (a136 * a99);
    a114 = (a52 / a48);
    a34 = (a34 - a114);
    a114 = (a145 * a150);
    a34 = (a34 - a114);
    a34 = (a34 / a66);
    a114 = (a11 * a34);
    a20 = (a20 * a66);
    a139 = (a12 * a108);
    a128 = (a106 * a100);
    a97 = (a78 * a109);
    a128 = (a128 + a97);
    a139 = (a139 - a128);
    a147 = (a79 * a147);
    a92 = (a92 * a138);
    a147 = (a147 + a92);
    a153 = (a153 * a21);
    a147 = (a147 + a153);
    a111 = (a111 * a116);
    a147 = (a147 + a111);
    a147 = (a147 * a57);
    a111 = (a147 / a1);
    a139 = (a139 - a111);
    a139 = (a2 * a139);
    a111 = (a45 + a139);
    a153 = (a27 * a111);
    a20 = (a20 + a153);
    a153 = (a135 * a108);
    a92 = (a39 * a100);
    a128 = (a77 * a109);
    a92 = (a92 + a128);
    a153 = (a153 - a92);
    a138 = (a134 * a138);
    a92 = (a79 * a81);
    a138 = (a138 - a92);
    a21 = (a64 * a21);
    a138 = (a138 + a21);
    a116 = (a19 * a116);
    a138 = (a138 + a116);
    a116 = (a141 * a147);
    a138 = (a138 + a116);
    a138 = (a138 * a60);
    a116 = (a138 / a1);
    a153 = (a153 - a116);
    a153 = (a2 * a153);
    a116 = (a46 + a153);
    a21 = (a4 * a116);
    a20 = (a20 + a21);
    a114 = (a114 - a20);
    a20 = (a145 * a44);
    a21 = (a136 / a151);
    a20 = (a20 - a21);
    a20 = (a20 / a66);
    a21 = (a20 * a121);
    a114 = (a114 + a21);
    a125 = (a125 - a114);
    a125 = (a125 * a66);
    a114 = (a125 / a48);
    a114 = (a2 * a114);
    a43 = (a43 + a114);
    a43 = (a43 / a16);
    a9 = (a9 - a43);
    if (res[1] != 0)
        res[1][3] = a9;
    a122 = (a7 * a122);
    a53 = (a53 + a122);
    a152 = (a7 * a152);
    a53 = (a53 + a152);
    a152 = (a111 / a66);
    a122 = (a49 / a1);
    a122 = (a122 / a57);
    a9 = (a147 * a122);
    a43 = (a129 * a89);
    a63 = (a63 / a18);
    a43 = (a43 - a63);
    a63 = (a142 * a62);
    a43 = (a43 - a63);
    a63 = (a49 * a100);
    a43 = (a43 - a63);
    a43 = (a43 / a57);
    a63 = (a106 * a43);
    a114 = (a142 * a95);
    a129 = (a129 / a88);
    a114 = (a114 - a129);
    a129 = (a49 * a109);
    a114 = (a114 - a129);
    a114 = (a114 / a57);
    a129 = (a78 * a114);
    a63 = (a63 + a129);
    a49 = (a49 * a108);
    a142 = (a142 / a101);
    a49 = (a49 - a142);
    a49 = (a49 / a57);
    a142 = (a12 * a49);
    a63 = (a63 + a142);
    a9 = (a9 - a63);
    a63 = (a118 / a57);
    a9 = (a9 + a63);
    a9 = (a2 * a9);
    a63 = (a50 + a9);
    a152 = (a152 / a63);
    a142 = (a152 * a125);
    a129 = (a56 * a99);
    a21 = (a17 / a48);
    a129 = (a129 - a21);
    a21 = (a119 * a150);
    a129 = (a129 - a21);
    a21 = (a111 * a34);
    a129 = (a129 - a21);
    a129 = (a129 / a63);
    a21 = (a11 * a129);
    a27 = (a27 * a63);
    a92 = (a138 * a122);
    a128 = (a39 * a43);
    a97 = (a77 * a114);
    a128 = (a128 + a97);
    a97 = (a135 * a49);
    a128 = (a128 + a97);
    a92 = (a92 - a128);
    a141 = (a115 * a141);
    a134 = (a134 * a106);
    a141 = (a141 + a134);
    a64 = (a64 * a78);
    a141 = (a141 + a64);
    a19 = (a19 * a12);
    a141 = (a141 + a19);
    a81 = (a81 * a147);
    a141 = (a141 + a81);
    a141 = (a141 * a60);
    a81 = (a141 / a57);
    a92 = (a92 - a81);
    a92 = (a2 * a92);
    a81 = (a55 + a92);
    a147 = (a4 * a81);
    a27 = (a27 + a147);
    a21 = (a21 - a27);
    a27 = (a119 * a44);
    a147 = (a56 / a151);
    a27 = (a27 - a147);
    a147 = (a111 * a20);
    a27 = (a27 - a147);
    a27 = (a27 / a63);
    a147 = (a27 * a121);
    a21 = (a21 + a147);
    a147 = (a111 * a144);
    a19 = (a119 / a137);
    a147 = (a147 - a19);
    a147 = (a147 / a63);
    a19 = (a147 * a31);
    a21 = (a21 + a19);
    a142 = (a142 - a21);
    a142 = (a142 * a63);
    a21 = (a142 / a48);
    a21 = (a2 * a21);
    a53 = (a53 + a21);
    a53 = (a53 / a16);
    a3 = (a3 - a53);
    if (res[1] != 0)
        res[1][4] = a3;
    a112 = (a7 * a112);
    a61 = (a61 + a112);
    a102 = (a7 * a102);
    a61 = (a61 + a102);
    a102 = (a81 / a63);
    a57 = (a117 / a57);
    a57 = (a57 / a60);
    a141 = (a141 * a57);
    a89 = (a132 * a89);
    a94 = (a94 / a18);
    a89 = (a89 - a94);
    a62 = (a86 * a62);
    a89 = (a89 - a62);
    a100 = (a25 * a100);
    a89 = (a89 - a100);
    a43 = (a117 * a43);
    a89 = (a89 - a43);
    a89 = (a89 / a60);
    a39 = (a39 * a89);
    a95 = (a86 * a95);
    a132 = (a132 / a88);
    a95 = (a95 - a132);
    a109 = (a25 * a109);
    a95 = (a95 - a109);
    a114 = (a117 * a114);
    a95 = (a95 - a114);
    a95 = (a95 / a60);
    a77 = (a77 * a95);
    a39 = (a39 + a77);
    a108 = (a25 * a108);
    a86 = (a86 / a101);
    a108 = (a108 - a86);
    a49 = (a117 * a49);
    a108 = (a108 - a49);
    a108 = (a108 / a60);
    a135 = (a135 * a108);
    a39 = (a39 + a135);
    a117 = (a117 * a122);
    a25 = (a25 / a1);
    a117 = (a117 - a25);
    a117 = (a117 / a60);
    a138 = (a138 * a117);
    a39 = (a39 + a138);
    a141 = (a141 - a39);
    a60 = (a22 / a60);
    a141 = (a141 + a60);
    a141 = (a2 * a141);
    a60 = (a59 + a141);
    a102 = (a102 / a60);
    a39 = (a102 * a142);
    a99 = (a131 * a99);
    a138 = (a148 / a48);
    a99 = (a99 - a138);
    a138 = (a35 * a150);
    a99 = (a99 - a138);
    a138 = (a116 * a34);
    a99 = (a99 - a138);
    a138 = (a81 * a129);
    a99 = (a99 - a138);
    a99 = (a99 / a60);
    a11 = (a11 * a99);
    a4 = (a4 * a60);
    a11 = (a11 - a4);
    a4 = (a35 * a44);
    a138 = (a131 / a151);
    a4 = (a4 - a138);
    a138 = (a116 * a20);
    a4 = (a4 - a138);
    a138 = (a81 * a27);
    a4 = (a4 - a138);
    a4 = (a4 / a60);
    a138 = (a4 * a121);
    a11 = (a11 + a138);
    a138 = (a116 * a144);
    a117 = (a35 / a137);
    a138 = (a138 - a117);
    a117 = (a81 * a147);
    a138 = (a138 - a117);
    a138 = (a138 / a60);
    a117 = (a138 * a31);
    a11 = (a11 + a117);
    a117 = (a81 * a152);
    a25 = (a116 / a66);
    a117 = (a117 - a25);
    a117 = (a117 / a60);
    a25 = (a117 * a125);
    a11 = (a11 + a25);
    a39 = (a39 - a11);
    a39 = (a39 * a60);
    a11 = (a39 / a48);
    a11 = (a2 * a11);
    a61 = (a61 + a11);
    a61 = (a61 / a16);
    a13 = (a13 - a61);
    if (res[1] != 0)
        res[1][5] = a13;
    a91 = (a7 * a91);
    a84 = (a84 + a91);
    a126 = (a7 * a126);
    a84 = (a84 + a126);
    a133 = (a133 / a48);
    a133 = (a133 / a151);
    a126 = (a121 * a133);
    a67 = (a67 / a151);
    a126 = (a126 + a67);
    a67 = (a70 * a136);
    a91 = (a72 * a56);
    a67 = (a67 + a91);
    a91 = (a73 * a131);
    a67 = (a67 + a91);
    a126 = (a126 - a67);
    a126 = (a2 * a126);
    a84 = (a84 + a126);
    a84 = (a84 / a16);
    a28 = (a28 + a84);
    if (res[1] != 0)
        res[1][6] = a28;
    a74 = (a7 * a74);
    a82 = (a82 + a74);
    a96 = (a7 * a96);
    a82 = (a82 + a96);
    a96 = (a31 * a133);
    a44 = (a68 * a44);
    a74 = (a70 * a145);
    a28 = (a72 * a119);
    a74 = (a74 + a28);
    a28 = (a73 * a35);
    a74 = (a74 + a28);
    a44 = (a44 + a74);
    a150 = (a150 * a121);
    a44 = (a44 + a150);
    a44 = (a44 * a137);
    a150 = (a44 / a151);
    a96 = (a96 - a150);
    a150 = (a76 * a136);
    a74 = (a6 * a56);
    a150 = (a150 + a74);
    a74 = (a0 * a131);
    a150 = (a150 + a74);
    a96 = (a96 - a150);
    a96 = (a2 * a96);
    a82 = (a82 + a96);
    a82 = (a82 / a16);
    a23 = (a23 + a82);
    if (res[1] != 0)
        res[1][7] = a23;
    a51 = (a7 * a51);
    a87 = (a87 + a51);
    a8 = (a7 * a8);
    a87 = (a87 + a8);
    a8 = (a125 * a133);
    a51 = (a34 * a121);
    a23 = (a68 * a20);
    a70 = (a70 * a66);
    a82 = (a72 * a111);
    a70 = (a70 + a82);
    a82 = (a73 * a116);
    a70 = (a70 + a82);
    a23 = (a23 - a70);
    a51 = (a51 - a23);
    a23 = (a144 * a44);
    a51 = (a51 + a23);
    a51 = (a51 * a66);
    a23 = (a51 / a151);
    a8 = (a8 - a23);
    a8 = (a2 * a8);
    a87 = (a87 + a8);
    a87 = (a87 / a16);
    a30 = (a30 + a87);
    if (res[1] != 0)
        res[1][8] = a30;
    a127 = (a7 * a127);
    a90 = (a90 + a127);
    a98 = (a7 * a98);
    a90 = (a90 + a98);
    a98 = (a142 * a133);
    a127 = (a129 * a121);
    a30 = (a68 * a27);
    a72 = (a72 * a63);
    a87 = (a73 * a81);
    a72 = (a72 + a87);
    a30 = (a30 - a72);
    a127 = (a127 - a30);
    a30 = (a147 * a44);
    a127 = (a127 - a30);
    a30 = (a152 * a51);
    a127 = (a127 + a30);
    a127 = (a127 * a63);
    a30 = (a127 / a151);
    a98 = (a98 - a30);
    a98 = (a2 * a98);
    a90 = (a90 + a98);
    a90 = (a90 / a16);
    a32 = (a32 + a90);
    if (res[1] != 0)
        res[1][9] = a32;
    a130 = (a7 * a130);
    a93 = (a93 + a130);
    a29 = (a7 * a29);
    a93 = (a93 + a29);
    a29 = (a39 * a133);
    a121 = (a99 * a121);
    a68 = (a68 * a4);
    a73 = (a73 * a60);
    a68 = (a68 - a73);
    a121 = (a121 - a68);
    a68 = (a138 * a44);
    a121 = (a121 - a68);
    a68 = (a117 * a51);
    a121 = (a121 - a68);
    a68 = (a102 * a127);
    a121 = (a121 + a68);
    a121 = (a121 * a60);
    a68 = (a121 / a151);
    a29 = (a29 - a68);
    a29 = (a2 * a29);
    a93 = (a93 + a29);
    a93 = (a93 / a16);
    a33 = (a33 + a93);
    if (res[1] != 0)
        res[1][10] = a33;
    a103 = (a7 * a103);
    a40 = (a40 + a103);
    a85 = (a7 * a85);
    a40 = (a40 + a85);
    a85 = (a15 / a151);
    a85 = (a85 / a137);
    a103 = (a44 * a85);
    a15 = (a15 * a133);
    a47 = (a47 / a48);
    a15 = (a15 - a47);
    a15 = (a15 / a137);
    a47 = (a31 * a15);
    a103 = (a103 - a47);
    a14 = (a14 / a137);
    a103 = (a103 + a14);
    a14 = (a76 * a145);
    a47 = (a6 * a119);
    a14 = (a14 + a47);
    a47 = (a0 * a35);
    a14 = (a14 + a47);
    a103 = (a103 - a14);
    a103 = (a2 * a103);
    a40 = (a40 + a103);
    a40 = (a40 / a16);
    a24 = (a24 + a40);
    if (res[1] != 0)
        res[1][11] = a24;
    a37 = (a7 * a37);
    a69 = (a69 + a37);
    a83 = (a7 * a83);
    a69 = (a69 + a83);
    a83 = (a51 * a85);
    a37 = (a125 * a15);
    a83 = (a83 - a37);
    a144 = (a75 * a144);
    a76 = (a76 * a66);
    a37 = (a6 * a111);
    a76 = (a76 + a37);
    a37 = (a0 * a116);
    a76 = (a76 + a37);
    a144 = (a144 + a76);
    a34 = (a34 * a31);
    a144 = (a144 + a34);
    a20 = (a20 * a44);
    a144 = (a144 + a20);
    a144 = (a144 * a66);
    a20 = (a144 / a137);
    a83 = (a83 - a20);
    a83 = (a2 * a83);
    a69 = (a69 + a83);
    a69 = (a69 / a16);
    a10 = (a10 + a69);
    if (res[1] != 0)
        res[1][12] = a10;
    a140 = (a7 * a140);
    a104 = (a104 + a140);
    a65 = (a7 * a65);
    a104 = (a104 + a65);
    a65 = (a127 * a85);
    a140 = (a142 * a15);
    a65 = (a65 - a140);
    a140 = (a129 * a31);
    a10 = (a75 * a147);
    a6 = (a6 * a63);
    a69 = (a0 * a81);
    a6 = (a6 + a69);
    a10 = (a10 - a6);
    a140 = (a140 - a10);
    a10 = (a27 * a44);
    a140 = (a140 + a10);
    a10 = (a152 * a144);
    a140 = (a140 + a10);
    a140 = (a140 * a63);
    a10 = (a140 / a137);
    a65 = (a65 - a10);
    a65 = (a2 * a65);
    a104 = (a104 + a65);
    a104 = (a104 / a16);
    a41 = (a41 + a104);
    if (res[1] != 0)
        res[1][13] = a41;
    a143 = (a7 * a143);
    a107 = (a107 + a143);
    a36 = (a7 * a36);
    a107 = (a107 + a36);
    a36 = (a121 * a85);
    a143 = (a39 * a15);
    a36 = (a36 - a143);
    a31 = (a99 * a31);
    a75 = (a75 * a138);
    a0 = (a0 * a60);
    a75 = (a75 - a0);
    a31 = (a31 - a75);
    a44 = (a4 * a44);
    a31 = (a31 + a44);
    a44 = (a117 * a144);
    a31 = (a31 - a44);
    a44 = (a102 * a140);
    a31 = (a31 + a44);
    a31 = (a31 * a60);
    a44 = (a31 / a137);
    a36 = (a36 - a44);
    a36 = (a2 * a36);
    a107 = (a107 + a36);
    a107 = (a107 / a16);
    a42 = (a42 + a107);
    if (res[1] != 0)
        res[1][14] = a42;
    a71 = (a7 * a71);
    a5 = (a5 + a71);
    a38 = (a7 * a38);
    a5 = (a5 + a38);
    a38 = (a145 / a137);
    a38 = (a38 / a66);
    a71 = (a144 * a38);
    a42 = (a136 * a133);
    a52 = (a52 / a48);
    a42 = (a42 - a52);
    a52 = (a145 * a15);
    a42 = (a42 - a52);
    a42 = (a42 / a66);
    a52 = (a125 * a42);
    a145 = (a145 * a85);
    a136 = (a136 / a151);
    a145 = (a145 - a136);
    a145 = (a145 / a66);
    a136 = (a51 * a145);
    a52 = (a52 + a136);
    a71 = (a71 - a52);
    a80 = (a80 / a66);
    a71 = (a71 + a80);
    a71 = (a2 * a71);
    a5 = (a5 + a71);
    a5 = (a5 / a16);
    a26 = (a26 + a5);
    if (res[1] != 0)
        res[1][15] = a26;
    a146 = (a7 * a146);
    a110 = (a110 + a146);
    a139 = (a7 * a139);
    a110 = (a110 + a139);
    a139 = (a140 * a38);
    a146 = (a142 * a42);
    a26 = (a127 * a145);
    a146 = (a146 + a26);
    a139 = (a139 - a146);
    a152 = (a79 * a152);
    a129 = (a129 * a125);
    a152 = (a152 + a129);
    a27 = (a27 * a51);
    a152 = (a152 + a27);
    a147 = (a147 * a144);
    a152 = (a152 + a147);
    a152 = (a152 * a63);
    a147 = (a152 / a66);
    a139 = (a139 - a147);
    a139 = (a2 * a139);
    a110 = (a110 + a139);
    a110 = (a110 / a16);
    a45 = (a45 + a110);
    if (res[1] != 0)
        res[1][16] = a45;
    a123 = (a7 * a123);
    a54 = (a54 + a123);
    a153 = (a7 * a153);
    a54 = (a54 + a153);
    a153 = (a31 * a38);
    a123 = (a39 * a42);
    a45 = (a121 * a145);
    a123 = (a123 + a45);
    a153 = (a153 - a123);
    a125 = (a99 * a125);
    a79 = (a79 * a117);
    a125 = (a125 - a79);
    a51 = (a4 * a51);
    a125 = (a125 + a51);
    a144 = (a138 * a144);
    a125 = (a125 + a144);
    a144 = (a102 * a152);
    a125 = (a125 + a144);
    a125 = (a125 * a60);
    a144 = (a125 / a66);
    a153 = (a153 - a144);
    a153 = (a2 * a153);
    a54 = (a54 + a153);
    a54 = (a54 / a16);
    a46 = (a46 + a54);
    if (res[1] != 0)
        res[1][17] = a46;
    a149 = (a7 * a149);
    a113 = (a113 + a149);
    a9 = (a7 * a9);
    a113 = (a113 + a9);
    a9 = (a111 / a66);
    a9 = (a9 / a63);
    a149 = (a152 * a9);
    a46 = (a56 * a133);
    a17 = (a17 / a48);
    a46 = (a46 - a17);
    a17 = (a119 * a15);
    a46 = (a46 - a17);
    a17 = (a111 * a42);
    a46 = (a46 - a17);
    a46 = (a46 / a63);
    a17 = (a142 * a46);
    a54 = (a119 * a85);
    a56 = (a56 / a151);
    a54 = (a54 - a56);
    a56 = (a111 * a145);
    a54 = (a54 - a56);
    a54 = (a54 / a63);
    a56 = (a127 * a54);
    a17 = (a17 + a56);
    a111 = (a111 * a38);
    a119 = (a119 / a137);
    a111 = (a111 - a119);
    a111 = (a111 / a63);
    a119 = (a140 * a111);
    a17 = (a17 + a119);
    a149 = (a149 - a17);
    a118 = (a118 / a63);
    a149 = (a149 + a118);
    a149 = (a2 * a149);
    a113 = (a113 + a149);
    a113 = (a113 / a16);
    a50 = (a50 + a113);
    if (res[1] != 0)
        res[1][18] = a50;
    a154 = (a7 * a154);
    a124 = (a124 + a154);
    a92 = (a7 * a92);
    a124 = (a124 + a92);
    a92 = (a125 * a9);
    a154 = (a39 * a46);
    a50 = (a121 * a54);
    a154 = (a154 + a50);
    a50 = (a31 * a111);
    a154 = (a154 + a50);
    a92 = (a92 - a154);
    a115 = (a115 * a102);
    a99 = (a99 * a142);
    a115 = (a115 + a99);
    a4 = (a4 * a127);
    a115 = (a115 + a4);
    a138 = (a138 * a140);
    a115 = (a115 + a138);
    a117 = (a117 * a152);
    a115 = (a115 + a117);
    a115 = (a115 * a60);
    a117 = (a115 / a63);
    a92 = (a92 - a117);
    a92 = (a2 * a92);
    a124 = (a124 + a92);
    a124 = (a124 / a16);
    a55 = (a55 + a124);
    if (res[1] != 0)
        res[1][19] = a55;
    a105 = (a7 * a105);
    a58 = (a58 + a105);
    a7 = (a7 * a141);
    a58 = (a58 + a7);
    a63 = (a81 / a63);
    a63 = (a63 / a60);
    a115 = (a115 * a63);
    a133 = (a131 * a133);
    a148 = (a148 / a48);
    a133 = (a133 - a148);
    a15 = (a35 * a15);
    a133 = (a133 - a15);
    a42 = (a116 * a42);
    a133 = (a133 - a42);
    a46 = (a81 * a46);
    a133 = (a133 - a46);
    a133 = (a133 / a60);
    a39 = (a39 * a133);
    a85 = (a35 * a85);
    a131 = (a131 / a151);
    a85 = (a85 - a131);
    a145 = (a116 * a145);
    a85 = (a85 - a145);
    a54 = (a81 * a54);
    a85 = (a85 - a54);
    a85 = (a85 / a60);
    a121 = (a121 * a85);
    a39 = (a39 + a121);
    a38 = (a116 * a38);
    a35 = (a35 / a137);
    a38 = (a38 - a35);
    a111 = (a81 * a111);
    a38 = (a38 - a111);
    a38 = (a38 / a60);
    a31 = (a31 * a38);
    a39 = (a39 + a31);
    a81 = (a81 * a9);
    a116 = (a116 / a66);
    a81 = (a81 - a116);
    a81 = (a81 / a60);
    a125 = (a125 * a81);
    a39 = (a39 + a125);
    a115 = (a115 - a39);
    a22 = (a22 / a60);
    a115 = (a115 + a22);
    a2 = (a2 * a115);
    a58 = (a58 + a2);
    a58 = (a58 / a16);
    a59 = (a59 + a58);
    if (res[1] != 0)
        res[1][20] = a59;
    return 0;
}

CASADI_SYMBOL_EXPORT int predict(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int predict_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int predict_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void predict_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int predict_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void predict_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void predict_incref(void)
{
}

CASADI_SYMBOL_EXPORT void predict_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int predict_n_in(void) { return 7; }

CASADI_SYMBOL_EXPORT casadi_int predict_n_out(void) { return 2; }

CASADI_SYMBOL_EXPORT casadi_real predict_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* predict_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "t";
    case 1:
        return "x";
    case 2:
        return "W";
    case 3:
        return "omega_m";
    case 4:
        return "std_gyro";
    case 5:
        return "sn_gyro_rw";
    case 6:
        return "dt";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* predict_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "x1";
    case 1:
        return "W1";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* predict_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s1;
    case 1:
        return casadi_s2;
    case 2:
        return casadi_s3;
    case 3:
        return casadi_s0;
    case 4:
        return casadi_s1;
    case 5:
        return casadi_s1;
    case 6:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* predict_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s3;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int predict_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 7;
    if (sz_res)
        *sz_res = 2;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

/* correct_mag:(x[7],W[6x6,21nz],y_b[3],decl,std_mag,beta_mag_c)->(x_mag[7],W_mag[6x6,21nz],beta_mag,r_mag,r_std_mag,error_code) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
    a0 = arg[0] ? arg[0][0] : 0;
    if (res[0] != 0)
        res[0][0] = a0;
    a1 = arg[0] ? arg[0][1] : 0;
    if (res[0] != 0)
        res[0][1] = a1;
    a2 = arg[0] ? arg[0][2] : 0;
    if (res[0] != 0)
        res[0][2] = a2;
    a3 = arg[0] ? arg[0][3] : 0;
    if (res[0] != 0)
        res[0][3] = a3;
    a3 = arg[0] ? arg[0][4] : 0;
    if (res[0] != 0)
        res[0][4] = a3;
    a3 = arg[0] ? arg[0][5] : 0;
    if (res[0] != 0)
        res[0][5] = a3;
    a3 = arg[0] ? arg[0][6] : 0;
    if (res[0] != 0)
        res[0][6] = a3;
    a3 = arg[1] ? arg[1][0] : 0;
    if (res[1] != 0)
        res[1][0] = a3;
    a4 = arg[1] ? arg[1][1] : 0;
    if (res[1] != 0)
        res[1][1] = a4;
    a4 = arg[1] ? arg[1][2] : 0;
    if (res[1] != 0)
        res[1][2] = a4;
    a5 = arg[1] ? arg[1][3] : 0;
    if (res[1] != 0)
        res[1][3] = a5;
    a5 = arg[1] ? arg[1][4] : 0;
    if (res[1] != 0)
        res[1][4] = a5;
    a5 = arg[1] ? arg[1][5] : 0;
    if (res[1] != 0)
        res[1][5] = a5;
    a5 = arg[1] ? arg[1][6] : 0;
    if (res[1] != 0)
        res[1][6] = a5;
    a6 = arg[1] ? arg[1][7] : 0;
    if (res[1] != 0)
        res[1][7] = a6;
    a7 = arg[1] ? arg[1][8] : 0;
    if (res[1] != 0)
        res[1][8] = a7;
    a7 = arg[1] ? arg[1][9] : 0;
    if (res[1] != 0)
        res[1][9] = a7;
    a7 = arg[1] ? arg[1][10] : 0;
    if (res[1] != 0)
        res[1][10] = a7;
    a7 = arg[1] ? arg[1][11] : 0;
    if (res[1] != 0)
        res[1][11] = a7;
    a8 = arg[1] ? arg[1][12] : 0;
    if (res[1] != 0)
        res[1][12] = a8;
    a8 = arg[1] ? arg[1][13] : 0;
    if (res[1] != 0)
        res[1][13] = a8;
    a8 = arg[1] ? arg[1][14] : 0;
    if (res[1] != 0)
        res[1][14] = a8;
    a8 = arg[1] ? arg[1][15] : 0;
    if (res[1] != 0)
        res[1][15] = a8;
    a8 = arg[1] ? arg[1][16] : 0;
    if (res[1] != 0)
        res[1][16] = a8;
    a8 = arg[1] ? arg[1][17] : 0;
    if (res[1] != 0)
        res[1][17] = a8;
    a8 = arg[1] ? arg[1][18] : 0;
    if (res[1] != 0)
        res[1][18] = a8;
    a8 = arg[1] ? arg[1][19] : 0;
    if (res[1] != 0)
        res[1][19] = a8;
    a8 = arg[1] ? arg[1][20] : 0;
    if (res[1] != 0)
        res[1][20] = a8;
    a8 = arg[3] ? arg[3][0] : 0;
    a9 = 8.;
    a10 = (a1 * a0);
    a10 = (a9 * a10);
    a11 = 4.;
    a12 = 1.;
    a13 = casadi_sq(a0);
    a14 = casadi_sq(a1);
    a13 = (a13 + a14);
    a14 = casadi_sq(a2);
    a13 = (a13 + a14);
    a14 = (a12 - a13);
    a11 = (a11 * a14);
    a14 = (a11 * a2);
    a10 = (a10 + a14);
    a13 = (a12 + a13);
    a13 = casadi_sq(a13);
    a10 = (a10 / a13);
    a14 = arg[2] ? arg[2][0] : 0;
    a15 = (a10 * a14);
    a16 = casadi_sq(a2);
    a17 = casadi_sq(a0);
    a16 = (a16 + a17);
    a16 = (a9 * a16);
    a16 = (a16 / a13);
    a16 = (a12 - a16);
    a17 = arg[2] ? arg[2][1] : 0;
    a18 = (a16 * a17);
    a15 = (a15 + a18);
    a18 = (a1 * a2);
    a18 = (a9 * a18);
    a19 = (a11 * a0);
    a18 = (a18 - a19);
    a18 = (a18 / a13);
    a19 = arg[2] ? arg[2][2] : 0;
    a20 = (a18 * a19);
    a15 = (a15 + a20);
    a20 = casadi_sq(a2);
    a21 = casadi_sq(a1);
    a20 = (a20 + a21);
    a20 = (a9 * a20);
    a20 = (a20 / a13);
    a20 = (a12 - a20);
    a14 = (a20 * a14);
    a21 = (a0 * a1);
    a21 = (a9 * a21);
    a22 = (a11 * a2);
    a21 = (a21 - a22);
    a21 = (a21 / a13);
    a17 = (a21 * a17);
    a14 = (a14 + a17);
    a0 = (a0 * a2);
    a0 = (a9 * a0);
    a11 = (a11 * a1);
    a0 = (a0 + a11);
    a0 = (a0 / a13);
    a19 = (a0 * a19);
    a14 = (a14 + a19);
    a15 = atan2(a15, a14);
    a15 = (a8 - a15);
    a14 = arg[4] ? arg[4][0] : 0;
    a19 = 2.0000000000000001e-01;
    a13 = casadi_sq(a3);
    a11 = casadi_sq(a5);
    a13 = (a13 + a11);
    a13 = sqrt(a13);
    a19 = (a19 * a13);
    a14 = (a14 + a19);
    a19 = 2.;
    a13 = casadi_fabs(a8);
    a11 = 9.9999999999999995e-08;
    a1 = (a13 < a11);
    a2 = 5.0000000000000000e-01;
    a17 = -4.1666666666666664e-02;
    a22 = casadi_sq(a13);
    a17 = (a17 * a22);
    a2 = (a2 + a17);
    a17 = 1.3888888888888889e-03;
    a22 = casadi_sq(a13);
    a22 = casadi_sq(a22);
    a17 = (a17 * a22);
    a2 = (a2 + a17);
    a2 = (a1 ? a2 : 0);
    a1 = (!a1);
    a17 = cos(a13);
    a17 = (a12 - a17);
    a22 = casadi_sq(a13);
    a17 = (a17 / a22);
    a1 = (a1 ? a17 : 0);
    a2 = (a2 + a1);
    a2 = (a2 * a8);
    a2 = (a2 * a8);
    a2 = (a12 - a2);
    a0 = (a0 * a2);
    a11 = (a13 < a11);
    a1 = -1.6666666666666666e-01;
    a17 = casadi_sq(a13);
    a1 = (a1 * a17);
    a1 = (a12 + a1);
    a17 = 8.3333333333333332e-03;
    a22 = casadi_sq(a13);
    a22 = casadi_sq(a22);
    a17 = (a17 * a22);
    a1 = (a1 + a17);
    a1 = (a11 ? a1 : 0);
    a11 = (!a11);
    a17 = sin(a13);
    a17 = (a17 / a13);
    a11 = (a11 ? a17 : 0);
    a1 = (a1 + a11);
    a1 = (a1 * a8);
    a18 = (a18 * a1);
    a0 = (a0 + a18);
    a20 = (a20 * a2);
    a10 = (a10 * a1);
    a20 = (a20 + a10);
    a20 = casadi_sq(a20);
    a21 = (a21 * a2);
    a16 = (a16 * a1);
    a21 = (a21 + a16);
    a21 = casadi_sq(a21);
    a20 = (a20 + a21);
    a21 = casadi_sq(a0);
    a20 = (a20 + a21);
    a20 = sqrt(a20);
    a0 = (a0 / a20);
    a0 = acos(a0);
    a0 = sin(a0);
    a20 = 1.0000000000000000e-03;
    a0 = casadi_fmax(a0, a20);
    a20 = (a19 * a0);
    a20 = (a14 / a20);
    a21 = casadi_fabs(a20);
    a21 = (a21 < a12);
    a20 = asin(a20);
    a20 = (a19 * a20);
    a20 = (a21 ? a20 : 0);
    a21 = (!a21);
    a21 = (a21 ? a14 : 0);
    a20 = (a20 + a21);
    a9 = (a9 * a20);
    a9 = casadi_sq(a9);
    a4 = casadi_sq(a4);
    a9 = (a9 + a4);
    a6 = casadi_sq(a6);
    a9 = (a9 + a6);
    a7 = casadi_sq(a7);
    a9 = (a9 + a7);
    a7 = (a15 / a9);
    a7 = (a7 * a15);
    a6 = arg[5] ? arg[5][0] : 0;
    a7 = (a7 / a6);
    if (res[2] != 0)
        res[2][0] = a7;
    if (res[3] != 0)
        res[3][0] = a15;
    a9 = sqrt(a9);
    if (res[4] != 0)
        res[4][0] = a9;
    a14 = (a14 / a19);
    a0 = (a0 < a14);
    a12 = (a0 ? a12 : 0);
    a0 = (!a0);
    a14 = 1.0000000000000001e-01;
    a3 = casadi_sq(a3);
    a5 = casadi_sq(a5);
    a3 = (a3 + a5);
    a3 = sqrt(a3);
    a14 = (a14 < a3);
    a14 = (a14 ? a19 : 0);
    a0 = (a0 ? a14 : 0);
    a12 = (a12 + a0);
    if (res[5] != 0)
        res[5][0] = a12;
    return 0;
}

CASADI_SYMBOL_EXPORT int correct_mag(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int correct_mag_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int correct_mag_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void correct_mag_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int correct_mag_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void correct_mag_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void correct_mag_incref(void)
{
}

CASADI_SYMBOL_EXPORT void correct_mag_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int correct_mag_n_in(void) { return 6; }

CASADI_SYMBOL_EXPORT casadi_int correct_mag_n_out(void) { return 6; }

CASADI_SYMBOL_EXPORT casadi_real correct_mag_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* correct_mag_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "x";
    case 1:
        return "W";
    case 2:
        return "y_b";
    case 3:
        return "decl";
    case 4:
        return "std_mag";
    case 5:
        return "beta_mag_c";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* correct_mag_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "x_mag";
    case 1:
        return "W_mag";
    case 2:
        return "beta_mag";
    case 3:
        return "r_mag";
    case 4:
        return "r_std_mag";
    case 5:
        return "error_code";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_mag_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s3;
    case 2:
        return casadi_s0;
    case 3:
        return casadi_s1;
    case 4:
        return casadi_s1;
    case 5:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_mag_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s3;
    case 2:
        return casadi_s1;
    case 3:
        return casadi_s1;
    case 4:
        return casadi_s1;
    case 5:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int correct_mag_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 6;
    if (sz_res)
        *sz_res = 6;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

/* correct_accel:(x[7],W[6x6,21nz],y_b[3],g,omega_b[3],std_accel,std_accel_omega,beta_accel_c)->(x_accel[7],W_accel[6x6,21nz],beta_accel,r_accel[2],r_std_accel[2],error_code) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
    a0 = arg[0] ? arg[0][0] : 0;
    if (res[0] != 0)
        res[0][0] = a0;
    a1 = arg[0] ? arg[0][1] : 0;
    if (res[0] != 0)
        res[0][1] = a1;
    a2 = arg[0] ? arg[0][2] : 0;
    if (res[0] != 0)
        res[0][2] = a2;
    a3 = arg[0] ? arg[0][3] : 0;
    if (res[0] != 0)
        res[0][3] = a3;
    a3 = arg[0] ? arg[0][4] : 0;
    if (res[0] != 0)
        res[0][4] = a3;
    a3 = arg[0] ? arg[0][5] : 0;
    if (res[0] != 0)
        res[0][5] = a3;
    a3 = arg[0] ? arg[0][6] : 0;
    if (res[0] != 0)
        res[0][6] = a3;
    a3 = arg[1] ? arg[1][0] : 0;
    if (res[1] != 0)
        res[1][0] = a3;
    a4 = arg[1] ? arg[1][1] : 0;
    if (res[1] != 0)
        res[1][1] = a4;
    a5 = arg[1] ? arg[1][2] : 0;
    if (res[1] != 0)
        res[1][2] = a5;
    a5 = arg[1] ? arg[1][3] : 0;
    if (res[1] != 0)
        res[1][3] = a5;
    a5 = arg[1] ? arg[1][4] : 0;
    if (res[1] != 0)
        res[1][4] = a5;
    a5 = arg[1] ? arg[1][5] : 0;
    if (res[1] != 0)
        res[1][5] = a5;
    a5 = arg[1] ? arg[1][6] : 0;
    if (res[1] != 0)
        res[1][6] = a5;
    a6 = arg[1] ? arg[1][7] : 0;
    if (res[1] != 0)
        res[1][7] = a6;
    a6 = arg[1] ? arg[1][8] : 0;
    if (res[1] != 0)
        res[1][8] = a6;
    a6 = arg[1] ? arg[1][9] : 0;
    if (res[1] != 0)
        res[1][9] = a6;
    a6 = arg[1] ? arg[1][10] : 0;
    if (res[1] != 0)
        res[1][10] = a6;
    a6 = arg[1] ? arg[1][11] : 0;
    if (res[1] != 0)
        res[1][11] = a6;
    a6 = arg[1] ? arg[1][12] : 0;
    if (res[1] != 0)
        res[1][12] = a6;
    a6 = arg[1] ? arg[1][13] : 0;
    if (res[1] != 0)
        res[1][13] = a6;
    a6 = arg[1] ? arg[1][14] : 0;
    if (res[1] != 0)
        res[1][14] = a6;
    a6 = arg[1] ? arg[1][15] : 0;
    if (res[1] != 0)
        res[1][15] = a6;
    a6 = arg[1] ? arg[1][16] : 0;
    if (res[1] != 0)
        res[1][16] = a6;
    a6 = arg[1] ? arg[1][17] : 0;
    if (res[1] != 0)
        res[1][17] = a6;
    a6 = arg[1] ? arg[1][18] : 0;
    if (res[1] != 0)
        res[1][18] = a6;
    a6 = arg[1] ? arg[1][19] : 0;
    if (res[1] != 0)
        res[1][19] = a6;
    a6 = arg[1] ? arg[1][20] : 0;
    if (res[1] != 0)
        res[1][20] = a6;
    a6 = 0.;
    a7 = 8.;
    a8 = (a1 * a0);
    a8 = (a7 * a8);
    a9 = 4.;
    a10 = 1.;
    a11 = casadi_sq(a0);
    a12 = casadi_sq(a1);
    a11 = (a11 + a12);
    a12 = casadi_sq(a2);
    a11 = (a11 + a12);
    a12 = (a10 - a11);
    a9 = (a9 * a12);
    a12 = (a9 * a2);
    a8 = (a8 + a12);
    a11 = (a10 + a11);
    a11 = casadi_sq(a11);
    a8 = (a8 / a11);
    a12 = arg[2] ? arg[2][0] : 0;
    a8 = (a8 * a12);
    a13 = casadi_sq(a2);
    a14 = casadi_sq(a0);
    a13 = (a13 + a14);
    a13 = (a7 * a13);
    a13 = (a13 / a11);
    a13 = (a10 - a13);
    a14 = arg[2] ? arg[2][1] : 0;
    a13 = (a13 * a14);
    a8 = (a8 + a13);
    a13 = (a1 * a2);
    a13 = (a7 * a13);
    a15 = (a9 * a0);
    a13 = (a13 - a15);
    a13 = (a13 / a11);
    a15 = arg[2] ? arg[2][2] : 0;
    a13 = (a13 * a15);
    a8 = (a8 + a13);
    a13 = casadi_sq(a12);
    a16 = casadi_sq(a14);
    a13 = (a13 + a16);
    a16 = casadi_sq(a15);
    a13 = (a13 + a16);
    a13 = sqrt(a13);
    a8 = (a8 / a13);
    a16 = casadi_sq(a8);
    a17 = casadi_sq(a2);
    a18 = casadi_sq(a1);
    a17 = (a17 + a18);
    a17 = (a7 * a17);
    a17 = (a17 / a11);
    a17 = (a10 - a17);
    a17 = (a17 * a12);
    a18 = (a0 * a1);
    a18 = (a7 * a18);
    a19 = (a9 * a2);
    a18 = (a18 - a19);
    a18 = (a18 / a11);
    a18 = (a18 * a14);
    a17 = (a17 + a18);
    a0 = (a0 * a2);
    a7 = (a7 * a0);
    a9 = (a9 * a1);
    a7 = (a7 + a9);
    a7 = (a7 / a11);
    a7 = (a7 * a15);
    a17 = (a17 + a7);
    a17 = (a17 / a13);
    a13 = casadi_sq(a17);
    a16 = (a16 + a13);
    a16 = sqrt(a16);
    a6 = (a6 < a16);
    a13 = casadi_fabs(a16);
    a13 = (a13 < a10);
    a6 = (a6 && a13);
    a13 = asin(a16);
    a8 = (a8 / a16);
    a8 = (a13 * a8);
    a7 = arg[5] ? arg[5][0] : 0;
    a11 = arg[4] ? arg[4][0] : 0;
    a11 = casadi_sq(a11);
    a9 = arg[4] ? arg[4][1] : 0;
    a9 = casadi_sq(a9);
    a11 = (a11 + a9);
    a9 = arg[4] ? arg[4][2] : 0;
    a9 = casadi_sq(a9);
    a11 = (a11 + a9);
    a9 = arg[6] ? arg[6][0] : 0;
    a11 = (a11 * a9);
    a7 = (a7 + a11);
    a11 = casadi_sq(a7);
    a9 = casadi_sq(a3);
    a11 = (a11 + a9);
    a9 = sqrt(a11);
    a3 = (a3 / a9);
    a1 = (a4 * a3);
    a0 = casadi_sq(a1);
    a2 = (a7 / a9);
    a2 = (a1 * a2);
    a2 = casadi_sq(a2);
    a7 = casadi_sq(a7);
    a2 = (a2 + a7);
    a3 = (a1 * a3);
    a4 = (a4 - a3);
    a4 = casadi_sq(a4);
    a2 = (a2 + a4);
    a5 = casadi_sq(a5);
    a2 = (a2 + a5);
    a0 = (a0 + a2);
    a5 = (a11 * a0);
    a4 = (a9 * a1);
    a3 = casadi_sq(a4);
    a5 = (a5 - a3);
    a0 = (a0 / a5);
    a0 = (a8 * a0);
    a17 = (a17 / a16);
    a13 = (a13 * a17);
    a1 = (a1 * a9);
    a1 = (a1 / a5);
    a1 = (a13 * a1);
    a0 = (a0 + a1);
    a0 = (a0 * a8);
    a4 = (a4 / a5);
    a4 = (a8 * a4);
    a11 = (a11 / a5);
    a11 = (a13 * a11);
    a4 = (a4 + a11);
    a4 = (a4 * a13);
    a0 = (a0 + a4);
    a0 = (a6 ? a0 : 0);
    a0 = (a6 ? a0 : 0);
    a4 = arg[7] ? arg[7][0] : 0;
    a0 = (a0 / a4);
    if (res[2] != 0)
        res[2][0] = a0;
    a8 = (-a8);
    a8 = (a6 ? a8 : 0);
    if (res[3] != 0)
        res[3][0] = a8;
    a6 = (a6 ? a13 : 0);
    if (res[3] != 0)
        res[3][1] = a6;
    if (res[4] != 0)
        res[4][0] = a9;
    a2 = sqrt(a2);
    if (res[4] != 0)
        res[4][1] = a2;
    a12 = casadi_sq(a12);
    a14 = casadi_sq(a14);
    a12 = (a12 + a14);
    a15 = casadi_sq(a15);
    a12 = (a12 + a15);
    a12 = sqrt(a12);
    a15 = arg[3] ? arg[3][0] : 0;
    a12 = (a12 - a15);
    a12 = casadi_fabs(a12);
    a12 = (a10 < a12);
    a12 = (a12 ? a10 : 0);
    if (res[5] != 0)
        res[5][0] = a12;
    return 0;
}

CASADI_SYMBOL_EXPORT int correct_accel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int correct_accel_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int correct_accel_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void correct_accel_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int correct_accel_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void correct_accel_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void correct_accel_incref(void)
{
}

CASADI_SYMBOL_EXPORT void correct_accel_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int correct_accel_n_in(void) { return 8; }

CASADI_SYMBOL_EXPORT casadi_int correct_accel_n_out(void) { return 6; }

CASADI_SYMBOL_EXPORT casadi_real correct_accel_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* correct_accel_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "x";
    case 1:
        return "W";
    case 2:
        return "y_b";
    case 3:
        return "g";
    case 4:
        return "omega_b";
    case 5:
        return "std_accel";
    case 6:
        return "std_accel_omega";
    case 7:
        return "beta_accel_c";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* correct_accel_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "x_accel";
    case 1:
        return "W_accel";
    case 2:
        return "beta_accel";
    case 3:
        return "r_accel";
    case 4:
        return "r_std_accel";
    case 5:
        return "error_code";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_accel_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s3;
    case 2:
        return casadi_s0;
    case 3:
        return casadi_s1;
    case 4:
        return casadi_s0;
    case 5:
        return casadi_s1;
    case 6:
        return casadi_s1;
    case 7:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_accel_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s3;
    case 2:
        return casadi_s1;
    case 3:
        return casadi_s4;
    case 4:
        return casadi_s4;
    case 5:
        return casadi_s1;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int correct_accel_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 8;
    if (sz_res)
        *sz_res = 6;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

/* get_state:(x[7])->(q[4],r[4],b_gyro[3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0 = arg[0] ? arg[0][3] : 0;
    a1 = 1.;
    a2 = arg[0] ? arg[0][0] : 0;
    a3 = casadi_sq(a2);
    a4 = arg[0] ? arg[0][1] : 0;
    a5 = casadi_sq(a4);
    a3 = (a3 + a5);
    a5 = arg[0] ? arg[0][2] : 0;
    a6 = casadi_sq(a5);
    a3 = (a3 + a6);
    a6 = (a1 - a3);
    a1 = (a1 + a3);
    a6 = (a6 / a1);
    a3 = (-a6);
    a3 = (a0 ? a3 : 0);
    a7 = (!a0);
    a6 = (a7 ? a6 : 0);
    a3 = (a3 + a6);
    if (res[0] != 0)
        res[0][0] = a3;
    a3 = 2.;
    a6 = (a3 * a2);
    a6 = (a6 / a1);
    a8 = (-a6);
    a8 = (a0 ? a8 : 0);
    a6 = (a7 ? a6 : 0);
    a8 = (a8 + a6);
    if (res[0] != 0)
        res[0][1] = a8;
    a8 = (a3 * a4);
    a8 = (a8 / a1);
    a6 = (-a8);
    a6 = (a0 ? a6 : 0);
    a8 = (a7 ? a8 : 0);
    a6 = (a6 + a8);
    if (res[0] != 0)
        res[0][2] = a6;
    a3 = (a3 * a5);
    a3 = (a3 / a1);
    a1 = (-a3);
    a1 = (a0 ? a1 : 0);
    a7 = (a7 ? a3 : 0);
    a1 = (a1 + a7);
    if (res[0] != 0)
        res[0][3] = a1;
    if (res[1] != 0)
        res[1][0] = a2;
    if (res[1] != 0)
        res[1][1] = a4;
    if (res[1] != 0)
        res[1][2] = a5;
    if (res[1] != 0)
        res[1][3] = a0;
    a0 = arg[0] ? arg[0][4] : 0;
    if (res[2] != 0)
        res[2][0] = a0;
    a0 = arg[0] ? arg[0][5] : 0;
    if (res[2] != 0)
        res[2][1] = a0;
    a0 = arg[0] ? arg[0][6] : 0;
    if (res[2] != 0)
        res[2][2] = a0;
    return 0;
}

CASADI_SYMBOL_EXPORT int get_state(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int get_state_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int get_state_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void get_state_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int get_state_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void get_state_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void get_state_incref(void)
{
}

CASADI_SYMBOL_EXPORT void get_state_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int get_state_n_in(void) { return 1; }

CASADI_SYMBOL_EXPORT casadi_int get_state_n_out(void) { return 3; }

CASADI_SYMBOL_EXPORT casadi_real get_state_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* get_state_name_in(casadi_int i)
{
    switch (i) {
    case 0:
        return "x";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* get_state_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "q";
    case 1:
        return "r";
    case 2:
        return "b_gyro";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* get_state_sparsity_in(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* get_state_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s5;
    case 1:
        return casadi_s5;
    case 2:
        return casadi_s0;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int get_state_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 1;
    if (sz_res)
        *sz_res = 3;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

/* constants:()->(x0[7],W0[6x6,6nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    casadi_real a0;
    a0 = 0.;
    if (res[0] != 0)
        res[0][0] = a0;
    if (res[0] != 0)
        res[0][1] = a0;
    if (res[0] != 0)
        res[0][2] = a0;
    if (res[0] != 0)
        res[0][3] = a0;
    if (res[0] != 0)
        res[0][4] = a0;
    if (res[0] != 0)
        res[0][5] = a0;
    if (res[0] != 0)
        res[0][6] = a0;
    a0 = 1.;
    if (res[1] != 0)
        res[1][0] = a0;
    if (res[1] != 0)
        res[1][1] = a0;
    if (res[1] != 0)
        res[1][2] = a0;
    a0 = 5.0000000000000003e-02;
    if (res[1] != 0)
        res[1][3] = a0;
    if (res[1] != 0)
        res[1][4] = a0;
    if (res[1] != 0)
        res[1][5] = a0;
    return 0;
}

CASADI_SYMBOL_EXPORT int constants(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
    return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int constants_alloc_mem(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT int constants_init_mem(int mem)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void constants_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int constants_checkout(void)
{
    return 0;
}

CASADI_SYMBOL_EXPORT void constants_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void constants_incref(void)
{
}

CASADI_SYMBOL_EXPORT void constants_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int constants_n_in(void) { return 0; }

CASADI_SYMBOL_EXPORT casadi_int constants_n_out(void) { return 2; }

CASADI_SYMBOL_EXPORT casadi_real constants_default_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* constants_name_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* constants_name_out(casadi_int i)
{
    switch (i) {
    case 0:
        return "x0";
    case 1:
        return "W0";
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* constants_sparsity_in(casadi_int i)
{
    switch (i) {
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* constants_sparsity_out(casadi_int i)
{
    switch (i) {
    case 0:
        return casadi_s2;
    case 1:
        return casadi_s6;
    default:
        return 0;
    }
}

CASADI_SYMBOL_EXPORT int constants_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w)
{
    if (sz_arg)
        *sz_arg = 0;
    if (sz_res)
        *sz_res = 2;
    if (sz_iw)
        *sz_iw = 0;
    if (sz_w)
        *sz_w = 0;
    return 0;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
