CONFIG_INPUT=y
CONFIG_INPUT_MODE_SYNCHRONOUS=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_CRSF=y
CONFIG_INPUT_CRSF_SEND_SYNC=y
CONFIG_INPUT_CRSF_REPORT_FILTER=1
CONFIG_INPUT_CRSF_THREAD_PRIORITY=1
CONFIG_INPUT_CRSF_THREAD_STACK_SIZE=2048
CONFIG_INPUT_CRSF_USE_DTCM_FOR_DMA_BUFFER=y
CONFIG_CODE_DATA_RELOCATION=y
CONFIG_POSIX_API=y
CONFIG_MAX_PTHREAD_MUTEX_COUNT=16
CONFIG_MAX_PTHREAD_COND_COUNT=8

CONFIG_DSP=y
CONFIG_DSP_BACKEND_CMSIS=y
CONFIG_CMSIS_DSP=y

CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_SENSOR_SHELL=y
CONFIG_ICM45686_STREAM=y
CONFIG_PINCTRL=y
CONFIG_CLOCK_CONTROL=y
CONFIG_DMA=y
CONFIG_MDIO=y
CONFIG_MDIO_SHELL=y
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_INIT_TIMEOUT=0
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
CONFIG_NET_SHELL=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_STATISTICS_PER_INTERFACE=y
CONFIG_NET_STATISTICS_USER_API=y
CONFIG_NET_STATISTICS_IPV4=y
CONFIG_NET_STATISTICS_ICMP=y
CONFIG_NET_STATISTICS_UDP=y
CONFIG_NET_STATISTICS_ETHERNET=y
CONFIG_ZENOH_PICO_SHELL=y
CONFIG_ZENOH_PICO_SHELL_MODE="client"
CONFIG_ZENOH_PICO_SHELL_CONNECT_LOCATOR="udp/192.0.2.2:7447"
CONFIG_ZENOH_PICO_SHELL_SUB_KEYEXPR="**"
CONFIG_ZENOH_PICO_SHELL_THREAD_PRIORITY=5
CONFIG_ZENOH_PICO_SHELL_THREAD_STACK_SIZE=4096
CONFIG_ZENOH_PICO_SHELL_RETRY_MS=1000
CONFIG_ZENOH_PICO_SHELL_MAX_PAYLOAD=512
CONFIG_ZENOH_PICO_SHELL_MAX_KEYEXPR=96
CONFIG_SPI_NXP_LPSPI_DMA=n
CONFIG_GNSS=y
