CONFIG_INPUT=y
CONFIG_INPUT_MODE_SYNCHRONOUS=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_CRSF=y
CONFIG_INPUT_CRSF_SEND_SYNC=y
CONFIG_INPUT_CRSF_REPORT_FILTER=1
CONFIG_INPUT_CRSF_THREAD_PRIORITY=1
CONFIG_INPUT_CRSF_THREAD_STACK_SIZE=2048
CONFIG_INPUT_CRSF_USE_DTCM_FOR_DMA_BUFFER=y

CONFIG_DSP=y
CONFIG_DSP_BACKEND_CMSIS=y
CONFIG_CMSIS_DSP=y

CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_SENSOR_SHELL=y
CONFIG_ICM45686_STREAM=y
CONFIG_PINCTRL=y
CONFIG_CLOCK_CONTROL=y
CONFIG_DMA=y
CONFIG_SPI_NXP_LPSPI_DMA=n
CONFIG_GNSS=y
