/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) gen_multirotor_ref_traj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* f_ref:(psi,psi_dot,psi_ddot,v_e[3],a_e[3],j_e[3],s_e[3],m,g,J_xx,J_yy,J_zz,J_xz)->(v_b[3],C_be[3x3],omega_eb_b[3],omega_dot_eb_b[3],M_b[3],T) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[7]? arg[7][0] : 0;
  a1=arg[4]? arg[4][2] : 0;
  a1=(a0*a1);
  a2=arg[8]? arg[8][0] : 0;
  a2=(a0*a2);
  a1=(a1-a2);
  a2=arg[4]? arg[4][0] : 0;
  a2=(a0*a2);
  a3=casadi_sq(a2);
  a4=arg[4]? arg[4][1] : 0;
  a4=(a0*a4);
  a5=casadi_sq(a4);
  a3=(a3+a5);
  a5=casadi_sq(a1);
  a3=(a3+a5);
  a3=sqrt(a3);
  a1=(a1/a3);
  a5=arg[0]? arg[0][0] : 0;
  a6=cos(a5);
  a7=(a1*a6);
  a5=sin(a5);
  a8=(a1*a5);
  a9=casadi_sq(a8);
  a10=casadi_sq(a7);
  a9=(a9+a10);
  a2=(a2/a3);
  a10=(a2*a5);
  a4=(a4/a3);
  a11=(a4*a6);
  a10=(a10-a11);
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a9=sqrt(a9);
  a7=(a7/a9);
  a11=(a7*a1);
  a10=(a10/a9);
  a12=(a10*a4);
  a11=(a11-a12);
  a12=arg[3]? arg[3][0] : 0;
  a13=(a11*a12);
  a14=(a10*a2);
  a8=(a8/a9);
  a9=(a8*a1);
  a14=(a14+a9);
  a9=arg[3]? arg[3][1] : 0;
  a15=(a14*a9);
  a13=(a13+a15);
  a15=(a8*a4);
  a16=(a7*a2);
  a15=(a15+a16);
  a16=arg[3]? arg[3][2] : 0;
  a17=(a15*a16);
  a13=(a13-a17);
  if (res[0]!=0) res[0][0]=a13;
  a13=(a7*a9);
  a17=(a8*a12);
  a13=(a13-a17);
  a17=(a10*a16);
  a13=(a13+a17);
  if (res[0]!=0) res[0][1]=a13;
  a12=(a2*a12);
  a9=(a4*a9);
  a12=(a12+a9);
  a16=(a1*a16);
  a12=(a12+a16);
  if (res[0]!=0) res[0][2]=a12;
  if (res[1]!=0) res[1][0]=a11;
  if (res[1]!=0) res[1][1]=a14;
  a12=(-a15);
  if (res[1]!=0) res[1][2]=a12;
  a12=(-a8);
  if (res[1]!=0) res[1][3]=a12;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a10;
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a4;
  if (res[1]!=0) res[1][8]=a1;
  a12=(a0/a3);
  a16=arg[5]? arg[5][1] : 0;
  a9=(a12*a16);
  a13=(a9*a7);
  a17=arg[5]? arg[5][0] : 0;
  a18=(a12*a17);
  a19=(a18*a8);
  a13=(a13-a19);
  a19=arg[5]? arg[5][2] : 0;
  a12=(a12*a19);
  a20=(a12*a10);
  a13=(a13+a20);
  a20=(-a13);
  if (res[2]!=0) res[2][0]=a20;
  a18=(a18*a11);
  a9=(a9*a14);
  a18=(a18+a9);
  a12=(a12*a15);
  a18=(a18-a12);
  if (res[2]!=0) res[2][1]=a18;
  a12=(-a2);
  a12=asin(a12);
  a9=cos(a12);
  a20=arg[1]? arg[1][0] : 0;
  a9=(a9*a20);
  a21=fabs(a12);
  a22=1.5707963267948966e+00;
  a21=(a21-a22);
  a21=fabs(a21);
  a22=1.0000000000000000e-03;
  a21=(a21<a22);
  a21=(!a21);
  a22=atan2(a4,a1);
  a21=(a21?a22:0);
  a22=cos(a21);
  a9=(a9/a22);
  a22=tan(a21);
  a22=(a18*a22);
  a9=(a9-a22);
  if (res[2]!=0) res[2][2]=a9;
  a22=(a0/a3);
  a23=arg[6]? arg[6][0] : 0;
  a24=(a14*a23);
  a25=arg[6]? arg[6][1] : 0;
  a26=(a7*a25);
  a24=(a24+a26);
  a26=arg[6]? arg[6][2] : 0;
  a27=(a4*a26);
  a24=(a24+a27);
  a22=(a22*a24);
  a24=2.;
  a24=(a24/a3);
  a27=(a0*a2);
  a27=(a27*a17);
  a17=(a0*a4);
  a17=(a17*a16);
  a27=(a27+a17);
  a17=(a0*a1);
  a17=(a17*a19);
  a27=(a27+a17);
  a17=(a13*a27);
  a17=(a24*a17);
  a22=(a22+a17);
  a17=(a9*a18);
  a22=(a22+a17);
  if (res[3]!=0) res[3][0]=a22;
  a17=(a9*a13);
  a0=(a0/a3);
  a23=(a11*a23);
  a25=(a8*a25);
  a23=(a23-a25);
  a26=(a2*a26);
  a23=(a23+a26);
  a0=(a0*a23);
  a27=(a18*a27);
  a24=(a24*a27);
  a0=(a0+a24);
  a17=(a17-a0);
  if (res[3]!=0) res[3][1]=a17;
  a0=arg[2]? arg[2][0] : 0;
  a24=(a6*a15);
  a27=(a11*a6);
  a23=(a5*a14);
  a27=(a27+a23);
  a24=(a24/a27);
  a23=(a24*a11);
  a26=(a5*a15);
  a26=(a26/a27);
  a25=(a26*a14);
  a23=(a23+a25);
  a11=(a11*a6);
  a14=(a5*a14);
  a11=(a11+a14);
  a11=(a11/a27);
  a15=(a11*a15);
  a23=(a23-a15);
  a23=(a23*a22);
  a0=(a0-a23);
  a7=(a26*a7);
  a8=(a24*a8);
  a7=(a7-a8);
  a10=(a11*a10);
  a7=(a7+a10);
  a7=(a7*a17);
  a0=(a0-a7);
  a7=sin(a12);
  a7=(a7*a20);
  a7=(a7-a13);
  a10=(a18*a7);
  a10=(a11*a10);
  a8=sin(a21);
  a12=cos(a12);
  a8=(a8*a12);
  a8=(a8*a20);
  a8=(a18-a8);
  a21=cos(a21);
  a8=(a8/a21);
  a6=(a8*a6);
  a6=(a20*a6);
  a6=(a24*a6);
  a7=(a9*a7);
  a8=(a8*a5);
  a20=(a20*a8);
  a7=(a7+a20);
  a7=(a26*a7);
  a6=(a6+a7);
  a10=(a10-a6);
  a0=(a0-a10);
  a24=(a24*a2);
  a26=(a26*a4);
  a24=(a24+a26);
  a11=(a11*a1);
  a24=(a24+a11);
  a0=(a0/a24);
  if (res[3]!=0) res[3][2]=a0;
  a24=arg[9]? arg[9][0] : 0;
  a11=(a24*a22);
  a1=arg[12]? arg[12][0] : 0;
  a26=(a1*a0);
  a11=(a11+a26);
  a26=arg[11]? arg[11][0] : 0;
  a4=(a26*a9);
  a2=(a1*a13);
  a4=(a4-a2);
  a2=(a18*a4);
  a10=arg[10]? arg[10][0] : 0;
  a6=(a10*a18);
  a7=(a9*a6);
  a2=(a2-a7);
  a11=(a11+a2);
  if (res[4]!=0) res[4][0]=a11;
  a10=(a10*a17);
  a17=(a1*a9);
  a24=(a24*a13);
  a17=(a17-a24);
  a9=(a9*a17);
  a4=(a13*a4);
  a9=(a9+a4);
  a10=(a10+a9);
  if (res[4]!=0) res[4][1]=a10;
  a1=(a1*a22);
  a26=(a26*a0);
  a1=(a1+a26);
  a13=(a13*a6);
  a18=(a18*a17);
  a13=(a13+a18);
  a1=(a1-a13);
  if (res[4]!=0) res[4][2]=a1;
  if (res[5]!=0) res[5][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ref(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_ref_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ref_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ref_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_ref_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ref_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_ref_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_ref_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_ref_n_in(void) { return 13;}

CASADI_SYMBOL_EXPORT casadi_int f_ref_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real f_ref_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ref_name_in(casadi_int i){
  switch (i) {
    case 0: return "psi";
    case 1: return "psi_dot";
    case 2: return "psi_ddot";
    case 3: return "v_e";
    case 4: return "a_e";
    case 5: return "j_e";
    case 6: return "s_e";
    case 7: return "m";
    case 8: return "g";
    case 9: return "J_xx";
    case 10: return "J_yy";
    case 11: return "J_zz";
    case 12: return "J_xz";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ref_name_out(casadi_int i){
  switch (i) {
    case 0: return "v_b";
    case 1: return "C_be";
    case 2: return "omega_eb_b";
    case 3: return "omega_dot_eb_b";
    case 4: return "M_b";
    case 5: return "T";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ref_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ref_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_ref_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
