#!/bin/bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CYECCA_PATH=$SCRIPT_DIR/../../modules/lib/cyecca

# disable virtual env if running (west venv)
PYTHON_PATH=`dirname -- "$(which python)"`
if [ -f $PYTHON_PATH/activate ]; then
	source $PYTHON_PATH/activate
	deactivate
fi

poetry install -C $CYECCA_PATH
