#!/bin/bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CYECCA_PATH=$SCRIPT_DIR/../../modules/lib/cyecca

# disable virtual env if running (west venv)
PYTHON_PATH=`dirname -- "$(which python)"`
if [ -f $PYTHON_PATH/activate ]; then
    source $PYTHON_PATH/activate
    deactivate
fi

unset PYTHONPATH
source ${CYECCA_PATH}/.venv/bin/activate
echo python path: $PYTHONPATH
echo python3 `which python3`

python3 $@

# vi: ts=4 sw=4 et
