# SPDX-License-Identifier: Apache-2.0
#
# CUBS2 deployment profile.
#
# native_sim deployment controller:
#   external joystick/manual-control node -> Zenoh/csyn -> controller -> Arduino PPM serial.

CONFIG_CUBS2_SITL=n
CONFIG_CUBS2_HOST_DEPLOY_IO=y
CONFIG_CUBS2_HOST_DEPLOY_JOYSTICK=n
CONFIG_CUBS2_SERIAL_BRIDGE_PPM_ARDUINO=y
CONFIG_CUBS2_PPM_MANUAL_OVERRIDE=y
