#!/usr/bin/env python3
"""
@author: Benjamin Perseghetti
@email: bperseghetti@rudislabs.com
"""
import jinja2
import os
import numpy as np
import argparse
import xmltodict
from pathlib import Path

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--hcdf')
    parser.add_argument('--template')
    parser.add_argument('--out')

    args = parser.parse_args()

    hcdf = Path(args.hcdf).resolve()
    template_dir = Path(args.template).parent.resolve()
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(hcdf) as fd:
        config = xmltodict.parse(fd.read(), process_namespaces=True)
    vehicle = config['hcdf']['vehicle']

    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(template_dir)))

    template_file = Path(args.template)

    if os.path.isfile(template_file):
        template = env.get_template(str(template_file.relative_to(template_dir)))
        result = template.render(vehicle)
        out = Path(args.out)
        out_file = out / template_file.stem
        
        with open(out_file, 'w') as f_out:
            print(f"{template} -> {out_file}")
            f_out.write(result)
    else:
        print(f"{template} does not exist!!!")
