name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.14
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Set path
        run: |
          echo "/github/home/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          apt update
          apt install curl python3-poetry clang-format-18 -y
          poetry config --list

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: cerebri

      - name: Initialize
        working-directory: cerebri
        run: |
          west init -l .
          west update
          ./scripts/cyecca_install

      - name: Format Check
        working-directory: cerebri
        run: |
          west format -c

      - name: Twister Tests
        working-directory: cerebri
        run: |
          west test
